# Use this file to store passwords to services that your server you use. When
# the server starts, the passwords will be automatically loaded and can be
# accessed from the `session.passwords` field. If you don't have access to a
# session object, passwords can also be accessed from
# `Serverpod.instance.passwords`. You can provide different passwords for
# different run configurations. If you want the same password for any
# configuration used, place it under `shared`.
#
# Note that this file should not be under version control. Store it in a safe
# place.

# Save passwords used across all configurations here.
shared:
  mySharedPassword: 'my password'

# These are passwords used when running the server locally in development mode
development:
  database: 'icTGQwuQD72rItA56ZJlgGuDQVzYY3vq'
  redis: 'bs8QCB2sFYiDILekwoR1BvbdelYlzbfu'

  # The service secret is used to communicate between servers and to access the
  # service protocol.
  serviceSecret: 'Ba7ddWC35ApFYJ1oSlJaAz25zmeppKRx'

  emailSecretHashPepper: 'GSGNscU3lRs3IFLWthRDlQ-nuhwsQRkk'
  jwtHmacSha512PrivateKey: 'u5kn0_gGDupRB6IHrtTdqw20DwrOYr1r'
  jwtRefreshTokenHashPepper: '9hZm7fbImNop8tbcmJ5ayTQ2xfM00pKD'
  # serverSideSessionKeyHashPepper: 'GZ4kJfrw-so6Pj2E5XVRgufPIy3JeGPA'

test:
  database: 'APi6TY2eFHvcAOXuSpE-8osYa3Hl_CTN'
  redis: 'SIpV-DDEuPOYHJRNKdw-yR5hmbDu-GON'

  emailSecretHashPepper: 'Q3fm9RNgrvBSzLaTWB0L2kjDzhE7HiBT'
  jwtHmacSha512PrivateKey: 'WzAmU9mvroDr4w05xCyWCRPPcNN8JK1E'
  jwtRefreshTokenHashPepper: 'Ou3quEe74-MSQnOe5sB4k3uV5Td-NLL9'
  # serverSideSessionKeyHashPepper: 'wt0v4tMjUbpZVr0VhKyz2txqKj_CtmHw'

# Passwords used in your staging environment if you use one. The default setup
# use a password for Redis.
staging:
  database: '3voExnemqzDa4dQn13_56hS_0aGvPWGe'
  serviceSecret: 'ambL38lZMUyboGbtOuM-WYvC9KGAWAwt'

  emailSecretHashPepper: 'HKVnIktBiopSqp6IanDzYLeWllA_L1kE'
  jwtHmacSha512PrivateKey: 'F8vmV4Vz7-Y8T88iFup2DjeWskOTW2ix'
  jwtRefreshTokenHashPepper: 'MBMNti4PGEmG94WRqahJU8DZfP9SHtjJ'
  # serverSideSessionKeyHashPepper: 'I69-3ZLZ9Y-DD2gv2CcvhQ50rCep83VV'

# Passwords used in production mode.
production:
  database: 'A3NQGkViJxEsr8Nt6O2xFNdrmQLQsBQv'
  serviceSecret: 'N59Mu9368l6DqoSPN4UB3TV5G6GlSFKj'

  emailSecretHashPepper: '622hmyH0Gu_ogZQjDo5tghN20v5qx2w5'
  jwtHmacSha512PrivateKey: 'FfsRmtfjBB13TxzzhuoRsS_STxKPU2tP'
  jwtRefreshTokenHashPepper: 'Pk7_ru5b_JPc6knyVG94TLlgSEasWAmx'
  # serverSideSessionKeyHashPepper: '59UD2H0VAoiNszObrrJInW4NV0HlmurS'
