import 'package:flutter_test/flutter_test.dart';
import 'package:preppsuite_flutter/features/warnings/application/dwd_areas.dart';
import 'package:preppsuite_flutter/features/warnings/application/warning_region_filter.dart';
import 'package:preppsuite_flutter/features/warnings/application/warning_relevance.dart';
import 'package:preppsuite_flutter/local_db/database.dart' as db;

/// Placing a MeteoAlarm warning.
///
/// The feed names its areas in words and a household follows five-digit
/// district keys. Before this the words went straight into `regionKey`,
/// where they could only ever fail to match — and a key that fails to
/// match does not read as "somewhere else", it reads as nowhere. Measured
/// against a live feed: 121 severe-weather warnings, not one of which
/// reached a household that had set a region.
void main() {
  // The real file's shape, in miniature: a district, a district whose
  // name has no key of its own, a sea area, and a comment.
  final areas = DwdAreas.parse('''
# Generated by tool/dwd_warncells.py — do not edit.
# name;district;state
Kreis Ahrweiler;07131;RP
Kreis Aurich;03452;NI
Kreis Aurich - Küste;;NI
Stadt Braunschweig;03101;NI
Insel Borkum;;NI
Alb-Donau-Kreis und Stadt Ulm;;BW
''');

  group('resolving a name', () {
    test('a district gives its key', () {
      expect(areas.regionKeyFor('Kreis Ahrweiler'), '07131');
      expect(areas.regionKeyFor('Stadt Braunschweig'), '03101');
    });

    test('a part of a district is placed in that district', () {
      // The feed splits some districts into a coastal and an inland
      // part. Those cells carry no key of their own, but the name in
      // front of the dash does — and falling back to the whole state
      // instead would put a storm surge warning on everybody in Lower
      // Saxony.
      expect(areas.regionKeyFor('Kreis Aurich - Küste'), '03452');
    });

    test('an area that spans districts falls back to its state', () {
      expect(areas.regionKeyFor('Alb-Donau-Kreis und Stadt Ulm'), 'BW');
      expect(areas.regionKeyFor('Insel Borkum'), 'NI');
    });

    test('an unknown name is nowhere in particular', () {
      // Null, not the name: null means "concerns everyone", which is the
      // safe reading for a warning that cannot be placed. The name would
      // mean "concerns nobody".
      expect(areas.regionKeyFor('Irgendwo'), isNull);
      expect(areas.regionKeyFor(''), isNull);
    });

    test('comments and short lines are skipped, not parsed', () {
      expect(areas.resolve('# name;district;state'), isNull);
    });
  });

  group('what the filter then does with it', () {
    db.Warning meteoAlarm(String areaDesc) => db.Warning(
      source: 'meteoalarm',
      externalId: 'x',
      countryCode: 'DE',
      regionKey: areas.regionKeyFor(areaDesc),
      severity: 'moderate',
      eventType: 'thunderstorm',
      headline: 'Test',
      effective: DateTime.utc(2026),
      sent: DateTime.utc(2026),
      updatedAt: DateTime.utc(2026),
      notified: false,
    );

    /// Braunschweig, which is the district 03101.
    const braunschweig = WarningRegionFilter(
      countryCode: 'DE',
      ownRegionKey: '031010000000',
      extraRegions: [],
    );

    test('a warning for another district no longer arrives', () {
      expect(
        isWarningRelevant(
          warning: meteoAlarm('Kreis Ahrweiler'),
          filter: braunschweig,
        ),
        isFalse,
      );
    });

    test('a warning for this district does', () {
      expect(
        isWarningRelevant(
          warning: meteoAlarm('Stadt Braunschweig'),
          filter: braunschweig,
        ),
        isTrue,
      );
    });

    test('a warning for the state does too', () {
      // Coarser than the district, and deliberately kept: an area that
      // cannot be narrowed down should reach too many people rather than
      // too few.
      expect(
        isWarningRelevant(
          warning: meteoAlarm('Insel Borkum'),
          filter: braunschweig,
        ),
        isTrue,
      );
    });

    test('an unplaceable warning reaches everyone', () {
      expect(
        isWarningRelevant(
          warning: meteoAlarm('Irgendwo'),
          filter: braunschweig,
        ),
        isTrue,
      );
    });
  });
}
