import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:preppsuite_flutter/features/warnings/application/dwd_areas.dart';
import 'package:preppsuite_flutter/features/warnings/application/warning_ingest.dart';
import 'package:preppsuite_flutter/features/warnings/application/warning_region_filter.dart';
import 'package:preppsuite_flutter/features/warnings/application/warning_relevance.dart';
import 'package:preppsuite_flutter/local_db/database.dart';
import 'package:preppsuite_flutter/model/categories.dart';

/// One real warning, against the real shipped table.
///
/// On 2026-09-14 a severe drinking-water alert issued by the
/// Vogelsbergkreis in Hesse appeared on a household in Braunschweig. The
/// warning is a KATWARN one: its id names no state, and its whole
/// statement of where it applies is "Teile von Lauterbach" -- which the
/// warncell table cannot resolve, because it holds a Lauterbach in
/// Baden-Wurttemberg, one in Thuringia, and files the Hessian one under
/// "Stadt Lauterbach (Hessen)". Unplaced means "concerns everyone".
///
/// `warning_ingest_test` covers the rule on a hand-written table. This
/// one reads `assets/dwd_warncells.csv` as shipped, because the rule is
/// only worth anything if the name it depends on is really in there --
/// and the file is regenerated by `tool/dwd_warncells.py` from a list
/// this project does not control.
void main() {
  const title =
      'Vogelsbergkreis meldet: Warnung Trinkwasserunfall. '
      'Gültig ab 14.09.2026, 15:29.';

  late DwdAreas areas;

  setUp(() {
    areas = DwdAreas.parse(
      File('assets/dwd_warncells.csv').readAsStringSync(),
    );
  });

  test('where it applies genuinely cannot be resolved', () {
    expect(areas.stateForAreaNames('Teile von Lauterbach'), isNull);
  });

  test('who issued it can be, and names one state', () {
    expect(bbkIssuerFromTitle(title), 'Vogelsbergkreis');
    expect(areas.stateForAreaNames('Vogelsbergkreis'), 'HE');
  });

  group('what the household sees', () {
    Warning warning(String? regionKey) => Warning(
      source: WarningSource.bbk.name,
      externalId: 'kat.6aa7f6b0995efd5eae12108e_public_topics',
      countryCode: 'DE',
      regionKey: regionKey,
      severity: WarningSeverity.severe.name,
      eventType: title,
      headline: title,
      effective: DateTime.utc(2026, 9, 14, 13, 29),
      sent: DateTime.utc(2026, 9, 14, 13, 29),
      notified: false,
      updatedAt: DateTime.utc(2026, 9, 14, 13, 29),
    );

    const braunschweig = WarningRegionFilter(
      countryCode: 'DE',
      ownRegionKey: '03101',
    );

    test('unplaced, it reached Lower Saxony -- the bug itself', () {
      expect(
        isWarningRelevant(warning: warning(null), filter: braunschweig),
        isTrue,
      );
    });

    test('placed in Hesse, it no longer does', () {
      expect(
        isWarningRelevant(warning: warning('HE'), filter: braunschweig),
        isFalse,
      );
    });

    test('and the people it concerns still get it', () {
      // The whole point of placing it rather than dropping it.
      const vogelsberg = WarningRegionFilter(
        countryCode: 'DE',
        ownRegionKey: '06535',
      );
      expect(
        isWarningRelevant(warning: warning('HE'), filter: vogelsberg),
        isTrue,
      );
    });
  });
}
