#!/usr/bin/env python3
"""Builds the lookup that turns a DWD area name into a district key.

MeteoAlarm names its areas in words — "Kreis Ahrweiler", "Stadt Ulm" —
and the app's regions are five-digit district keys. Without a bridge
between the two, every MeteoAlarm warning carries a region nothing can
match, and the relevance check drops it: severe-weather warnings that
never reach anybody.

The bridge is the DWD's own warncell list, which names exactly the same
areas and whose cell ids carry the district key: a cell beginning with 1
or 8 is `1` or `8`, then the five-digit key, then three more digits.

Run it when the warncell list changes, which is rarely:

    tool/dwd_warncells.py
"""

import csv
import io
import sys
import urllib.request
from typing import Optional

SOURCE = (
    "https://www.dwd.de/DE/leistungen/opendata/help/warnungen/"
    "cap_warncellids_csv.csv?__blob=publicationFile&v=3"
)
TARGET = "preppsuite_flutter/assets/dwd_warncells.csv"


def district_of(cell_id):  # -> Optional[str]
    """The five-digit district key a cell id carries, if it carries one.

    Cells beginning with 1 (a district) or 8 (a municipality inside one)
    do. The rest — sea areas, islands, areas spanning several districts —
    do not, and are left to their state instead.
    """
    if len(cell_id) == 9 and cell_id[0] in "18":
        return cell_id[1:6]
    return None


def main() -> int:
    with urllib.request.urlopen(SOURCE, timeout=60) as response:
        raw = response.read().decode("utf-8-sig")

    rows = []
    for row in csv.DictReader(io.StringIO(raw), delimiter=";"):
        name = (row.get("NAME") or "").strip()
        cell = (row.get("WARNCELLID") or "").strip()
        state = (row.get("BL") or "").strip()
        if not name or not cell:
            continue
        rows.append((name, district_of(cell) or "", state))

    # Sorted and de-duplicated so the file is stable between runs: a
    # generated asset that reshuffles itself makes every regeneration
    # look like a change.
    unique = sorted(set(rows))

    with open(TARGET, "w", encoding="utf-8", newline="\n") as out:
        out.write("# Generated by tool/dwd_warncells.py — do not edit.\n")
        out.write("# name;district;state\n")
        for name, district, state in unique:
            if ";" in name:
                continue  # would break the format; none exist today
            out.write(f"{name};{district};{state}\n")

    with_district = sum(1 for _, d, _ in unique if d)
    print(f"{len(unique)} Gebiete, davon {with_district} mit Kreisschluessel")
    print(f"-> {TARGET}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
