import 'package:flutter/services.dart' show rootBundle;

/// Where a DWD warning area sits, as far as it can be pinned down.
///
/// [district] is a five-digit Kreisschlüssel, [state] the two-letter code
/// the rest of the app already uses (`GermanState.bbkCode`). Sea areas and
/// areas spanning several districts have only the second; a few have
/// neither.
class DwdArea {
  const DwdArea({this.district, this.state});

  final String? district;
  final String? state;

  bool get isEmpty => district == null && state == null;
}

/// Turns a DWD area name into something the region filter can match.
///
/// MeteoAlarm names its areas in words — "Kreis Ahrweiler", "Stadt Ulm" —
/// while a household follows five-digit district keys. Without a bridge
/// the two never meet, and `isWarningRelevant` drops every MeteoAlarm
/// warning as belonging to somebody else. Measured on a live feed: 121
/// severe-weather warnings, none of which reached a household that had
/// set a region.
///
/// The bridge is the DWD's own warncell list, which names exactly the
/// same areas — all eighty in that feed matched it exactly — and whose
/// cell ids carry the district key. It is regenerated by
/// `tool/dwd_warncells.py`.
class DwdAreas {
  DwdAreas._(this._byName);

  final Map<String, DwdArea> _byName;

  static const assetPath = 'assets/dwd_warncells.csv';

  /// Loaded once and kept: the table is a third of a megabyte and the
  /// poller runs every fifteen minutes.
  static Future<DwdAreas>? _loading;

  static Future<DwdAreas> load() =>
      _loading ??= rootBundle.loadString(assetPath).then(parse);

  /// Takes the text rather than reading it, so the parsing can be tested
  /// without a bundle underneath it.
  static DwdAreas parse(String text) {
    final byName = <String, DwdArea>{};
    for (final line in text.split('\n')) {
      if (line.isEmpty || line.startsWith('#')) continue;

      final parts = line.split(';');
      if (parts.length < 3) continue;

      final name = parts[0];
      if (name.isEmpty) continue;

      byName[name] = DwdArea(
        district: parts[1].isEmpty ? null : parts[1],
        state: parts[2].isEmpty ? null : parts[2],
      );
    }
    return DwdAreas._(byName);
  }

  /// The area behind a MeteoAlarm `areaDesc`, or null for a name the list
  /// does not know.
  DwdArea? resolve(String areaDesc) {
    final name = areaDesc.trim();
    if (name.isEmpty) return null;

    final exact = _byName[name];
    if (exact?.district != null) return exact;

    // The feed splits some districts into parts — "Kreis Aurich - Küste",
    // "Kreis Cuxhaven - Binnenland". Those cells are in the list too, but
    // carry no district key of their own; the name in front of the dash
    // is the district and does. Tried only after the exact match came
    // back without one, so a genuine hit is never second-guessed —
    // otherwise a coastal warning would fall back to its whole state.
    final dash = name.indexOf(' - ');
    if (dash > 0) {
      final parent = _byName[name.substring(0, dash).trim()];
      if (parent?.district != null) return parent;
    }

    return exact;
  }

  /// What to store as a warning's `regionKey`.
  ///
  /// The district where there is one, else the state, else null — and
  /// null is not a failure but the safe reading: a warning whose area
  /// cannot be placed concerns everyone rather than nobody. Free text
  /// must never end up here; it can only ever fail to match, which is
  /// how these warnings came to be dropped in the first place.
  String? regionKeyFor(String areaDesc) {
    final area = resolve(areaDesc);
    if (area == null) return null;
    return area.district ?? area.state;
  }
}
