import 'package:flutter/services.dart' show rootBundle;

/// Where a DWD warning area sits, as far as it can be pinned down.
///
/// [district] is a five-digit Kreisschlüssel, [state] the two-letter code
/// the rest of the app already uses (`GermanState.bbkCode`). Sea areas and
/// areas spanning several districts have only the second; a few have
/// neither.
class DwdArea {
  const DwdArea({this.district, this.state});

  final String? district;
  final String? state;

  bool get isEmpty => district == null && state == null;
}

/// Turns a DWD area name into something the region filter can match.
///
/// MeteoAlarm names its areas in words — "Kreis Ahrweiler", "Stadt Ulm" —
/// while a household follows five-digit district keys. Without a bridge
/// the two never meet, and `isWarningRelevant` drops every MeteoAlarm
/// warning as belonging to somebody else. Measured on a live feed: 121
/// severe-weather warnings, none of which reached a household that had
/// set a region.
///
/// The bridge is the DWD's own warncell list, which names exactly the
/// same areas — all eighty in that feed matched it exactly — and whose
/// cell ids carry the district key. It is regenerated by
/// `tool/dwd_warncells.py`.
class DwdAreas {
  DwdAreas._(this._byName, this._statesByCore, this._districtNames);

  final Map<String, DwdArea> _byName;

  /// Every area name reduced to its bare place name, mapped to the states
  /// that name occurs in. What this is for: placing a warning whose only
  /// statement of where it applies is a sentence -- see
  /// [stateForAreaNames].
  final Map<String, Set<String>> _statesByCore;

  /// A district key mapped to the name to show a person for it. Built
  /// here rather than looked up on demand, because the table is a third
  /// of a megabyte and the answer never changes.
  final Map<String, String> _districtNames;

  static const assetPath = 'assets/dwd_warncells.csv';

  /// Loaded once and kept: the table is a third of a megabyte and the
  /// poller runs every fifteen minutes.
  static Future<DwdAreas>? _loading;

  static Future<DwdAreas> load() =>
      _loading ??= rootBundle.loadString(assetPath).then(parse);

  /// Takes the text rather than reading it, so the parsing can be tested
  /// without a bundle underneath it.
  static DwdAreas parse(String text) {
    final byName = <String, DwdArea>{};
    final statesByCore = <String, Set<String>>{};
    final namesByDistrict = <String, List<String>>{};

    for (final line in text.split('\n')) {
      if (line.isEmpty || line.startsWith('#')) continue;

      final parts = line.split(';');
      if (parts.length < 3) continue;

      final name = parts[0];
      if (name.isEmpty) continue;

      final district = parts[1].isEmpty ? null : parts[1];
      final state = parts[2].isEmpty ? null : parts[2];
      byName[name] = DwdArea(district: district, state: state);

      if (state != null) {
        final core = areaNameCore(name);
        if (core.isNotEmpty) {
          (statesByCore[core] ??= <String>{}).add(state);
        }
      }
      if (district != null) {
        (namesByDistrict[district] ??= <String>[]).add(name);
      }
    }

    return DwdAreas._(byName, statesByCore, {
      for (final entry in namesByDistrict.entries)
        entry.key: _districtNameFrom(entry.value),
    });
  }

  /// Which of a district's names to put in front of a person.
  ///
  /// The table is Gemeinde-level, so one district key carries up to 235
  /// names -- every village in it. A name containing "kreis" is the
  /// district's own ("Kreis Borken", but also "Westerwaldkreis" and
  /// "Eifelkreis Bitburg-Prum", which is why this is a search and not a
  /// prefix); the shortest of those is the district and not a town in it.
  /// Only a kreisfreie Stadt has no such name, and there "Stadt X" is the
  /// district. Checked against all 401 districts in the table: 291 take
  /// the first branch, 110 the second, none the third.
  static String _districtNameFrom(List<String> names) {
    String? shortest(bool Function(String) accepts) {
      String? best;
      for (final name in names) {
        if (!accepts(name)) continue;
        if (best == null ||
            name.length < best.length ||
            (name.length == best.length && name.compareTo(best) < 0)) {
          best = name;
        }
      }
      return best;
    }

    return shortest((name) => name.toLowerCase().contains('kreis')) ??
        shortest((name) => name.startsWith('Stadt ')) ??
        shortest((_) => true)!;
  }

  /// The area behind a MeteoAlarm `areaDesc`, or null for a name the list
  /// does not know.
  DwdArea? resolve(String areaDesc) {
    final name = areaDesc.trim();
    if (name.isEmpty) return null;

    final exact = _byName[name];
    if (exact?.district != null) return exact;

    // The feed splits some districts into parts — "Kreis Aurich - Küste",
    // "Kreis Cuxhaven - Binnenland". Those cells are in the list too, but
    // carry no district key of their own; the name in front of the dash
    // is the district and does. Tried only after the exact match came
    // back without one, so a genuine hit is never second-guessed —
    // otherwise a coastal warning would fall back to its whole state.
    final dash = name.indexOf(' - ');
    if (dash > 0) {
      final parent = _byName[name.substring(0, dash).trim()];
      if (parent?.district != null) return parent;
    }

    return exact;
  }

  /// A name with its administrative prefix taken off, lowercased.
  ///
  /// The point is that the two sides spell the same place differently:
  /// the warncell table says "Kreis Alzey-Worms" and KATWARN says
  /// "LKr. Alzey-Worms". Reducing both to `alzey-worms` lets them meet.
  ///
  /// Only a *leading* prefix is removed, which is why "Westerwaldkreis"
  /// and "Rhein-Pfalz-Kreis" survive intact -- there the word is part of
  /// the name, and stripping it would make two different districts look
  /// like the same place.
  static String areaNameCore(String name) {
    var value = name.trim().toLowerCase();

    var stripped = true;
    while (stripped) {
      stripped = false;
      for (final prefix in _namePrefixes) {
        if (value == prefix) {
          value = '';
          stripped = true;
          break;
        }
        if (value.startsWith('$prefix ')) {
          value = value.substring(prefix.length).trim();
          stripped = true;
          break;
        }
      }
    }

    return value
        .replaceAll(RegExp(r'\s+'), ' ')
        .replaceAll(RegExp(r'^[.\-\s]+|[.\-\s]+$'), '');
  }

  /// Longest first, so "landkreis" is never shortened to "kreis" with a
  /// stray "land" left in front of the name.
  static const _namePrefixes = [
    'gemeindefreies gebiet',
    'verbandsgemeinde',
    'stadtgebiet',
    'landkreis',
    'teile von',
    'teile des',
    'gemeinde',
    'kreis',
    'stadt',
    'lkr.',
    'lkr',
    'kr.',
    'sk',
    'lk',
    'kr',
  ];

  /// Fragments that name no place and must not count as an unresolved
  /// one either.
  static const _filler = {'umland', 'umgebung', 'umkreis', 'und umland'};

  /// The one Bundesland a free-text area description is about, or null.
  ///
  /// This exists for the warnings whose id says nothing about where they
  /// apply. KATWARN is the case that forced it: its ids carry no state
  /// (`kat.6aa2cd02995efd5eae120ffb_public_topics`), so an earthquake
  /// near Worms was placed nowhere, which means everywhere -- and it
  /// reached a household in Braunschweig as if it concerned them. The
  /// text it does carry is "Teile von LKr. Alzey-Worms, LKr. Bad
  /// Durkheim, Rhein-Pfalz-Kreis und Umland".
  ///
  /// Deliberately unanimous-or-nothing, and deliberately only as precise
  /// as a state. A warning whose districts span two states stays
  /// unplaced, because for a civil-protection alert too many people is
  /// the safe error and this is the one place where narrowing can hide
  /// one. Nothing here ever produces a district key: these names come
  /// from prose, and a single misread word would hide a warning from the
  /// district it is actually about.
  String? stateForAreaNames(String areaDesc) {
    final states = <String>{};
    var matched = 0;

    for (final fragment in areaDesc.split(RegExp(r',|\bund\b|&|/|\n'))) {
      final core = areaNameCore(fragment);
      if (core.isEmpty || _filler.contains(core)) continue;

      final found = _statesByCore[core];
      if (found == null) continue;
      matched++;
      states.addAll(found);
    }

    if (matched == 0 || states.length != 1) return null;
    return states.first;
  }

  /// What a five-digit district key is the key *of*, for showing back to
  /// the person who typed it.
  ///
  /// The settings screen used to print `031010000000` and nothing else,
  /// which is unverifiable: it is exactly as plausible as the key for
  /// somewhere else entirely. Null for a key the table does not know,
  /// which is itself worth saying.
  DwdDistrict? describeDistrict(String districtKey) {
    if (districtKey.length < 5) return null;
    final key = districtKey.substring(0, 5);

    final name = _districtNames[key];
    if (name == null) return null;
    return DwdDistrict(key: key, name: name, state: _byName[name]?.state);
  }

  /// What to store as a warning's `regionKey`.
  ///
  /// The district where there is one, else the state, else null — and
  /// null is not a failure but the safe reading: a warning whose area
  /// cannot be placed concerns everyone rather than nobody. Free text
  /// must never end up here; it can only ever fail to match, which is
  /// how these warnings came to be dropped in the first place.
  String? regionKeyFor(String areaDesc) {
    final area = resolve(areaDesc);
    if (area == null) return null;
    return area.district ?? area.state;
  }
}

/// A district key resolved to something readable.
class DwdDistrict {
  const DwdDistrict({required this.key, required this.name, this.state});

  /// The five-digit Kreisschluessel.
  final String key;

  /// The district's own name, e.g. "Stadt Braunschweig".
  final String name;

  /// Two-letter state code, or null for the handful of table rows that
  /// name none.
  final String? state;
}
