// GENERATED by tool/first_aid/generate.dart from
// content/first_aid/de.md. Do not edit: change the
// Markdown and run the generator again. The reasons behind the
// text are written down there, beside it.

import 'first_aid_guide.dart';
import 'poison_centres.dart';

const firstAidGuidesDe = <FirstAidGuide>[
  FirstAidGuide(
    id: 'emergency-call',
    group: FirstAidGroup.basics,
    title: 'Notruf absetzen',
    when: 'Immer zuerst, sobald jemand ernsthaft in Gefahr ist.',
    steps: [
      FirstAidStep(
        'Wo ist es passiert?',
        detail: 'Ort, Straße, Hausnummer, Stockwerk. Auf dem Land: Gemeinde und was in der Nähe steht.',
      ),
      FirstAidStep(
        'Was ist passiert?',
        detail: 'Ein Satz genügt: Sturz vom Dach, Person atmet nicht, Auto gegen Baum.',
      ),
      FirstAidStep('Wie viele Verletzte?'),
      FirstAidStep(
        'Welche Verletzungen?',
        detail: 'Was du siehst, nicht was du vermutest.',
      ),
      FirstAidStep(
        'Warten auf Rückfragen.',
        detail: 'Die Leitstelle beendet das Gespräch, nicht du. Sie leitet dich am Telefon an, bis der Rettungsdienst da ist.',
      ),
    ],
    cautions: [
      'Nicht auflegen, bevor die Leitstelle es sagt.',
      'Kein Netz heißt nicht kein Notruf: 112 geht auch ohne Guthaben und in vielen Fällen über ein fremdes Netz.',
    ],
    facts: [
      FirstAidFact('Rettungsdienst und Feuerwehr', '112'),
      FirstAidFact('Polizei', '110'),
      FirstAidFact('Ärztlicher Bereitschaftsdienst', '116 117'),
      FirstAidFact('Europaweit', '112'),
    ],
    source: 'Bundesamt für Bevölkerungsschutz und Katastrophenhilfe',
  ),
  FirstAidGuide(
    id: 'unresponsive',
    group: FirstAidGroup.basics,
    title: 'Bewusstlose Person prüfen',
    when: 'Jemand liegt da und reagiert nicht. Das ist der Anfang von allem, was danach kommt.',
    steps: [
      FirstAidStep(
        'Eigene Sicherheit zuerst.',
        detail: 'Verkehr, Strom, Rauch, Gas. Ein zweiter Verletzter hilft niemandem.',
      ),
      FirstAidStep('Laut ansprechen und an den Schultern rütteln.'),
      FirstAidStep(
        'Keine Reaktion? Um Hilfe rufen und 112 wählen.',
        detail: 'Telefon auf Lautsprecher, damit die Hände frei bleiben.',
      ),
      FirstAidStep(
        'Atemwege frei machen.',
        detail: 'Eine Hand auf die Stirn, zwei Finger der anderen unter das Kinn, Kopf vorsichtig nach hinten neigen.',
      ),
      FirstAidStep(
        'Höchstens 10 Sekunden auf die Atmung achten.',
        detail: 'Hebt sich der Brustkorb? Hörst du Atemgeräusche? Spürst du die Luft an deiner Wange?',
      ),
      FirstAidStep(
        'Atmet normal: stabile Seitenlage, Atmung weiter beobachten.',
      ),
      FirstAidStep(
        'Atmet nicht normal: sofort mit der Wiederbelebung beginnen.',
      ),
    ],
    cautions: [
      'Einzelne schnappende Atemzüge sind keine normale Atmung. Diese Schnappatmung ist in den ersten Minuten nach einem Herzstillstand häufig und wird regelmäßig für Atmung gehalten – im Zweifel gilt sie als Atemstillstand.',
      'Im Zweifel drücken. Herzdruckmassage bei jemandem, dessen Herz noch schlägt, richtet weit weniger Schaden an als unterlassene Wiederbelebung bei jemandem, dessen Herz steht.',
    ],
    source: 'Reanimationsleitlinien 2025 des European Resuscitation Council (ERC), deutsche Fassung des German Resuscitation Council',
  ),
  FirstAidGuide(
    id: 'cpr-adult',
    group: FirstAidGroup.lifeThreatening,
    title: 'Wiederbelebung – Erwachsener',
    when: 'Die Person reagiert nicht und atmet nicht normal.',
    callFirst: true,
    steps: [
      FirstAidStep(
        '112 anrufen und einen Defibrillator holen lassen.',
        detail: 'Bist du allein: erst anrufen, Lautsprecher an, dann drücken. Ist jemand bei dir: er ruft an und holt den AED, du drückst.',
      ),
      FirstAidStep(
        'Sofort anfangen, wo die Person liegt.',
        detail: 'Kleidung nur öffnen, wenn du sonst den Druckpunkt nicht findest. Auf eine harte Unterlage umlagern nur, wenn es in Sekunden geht — jede Verzögerung kostet mehr, als die weiche Unterlage.',
      ),
      FirstAidStep(
        'Einen Handballen auf die Mitte des Brustkorbs setzen, die zweite Hand darüber, Finger verschränken.',
        detail: 'Mitte des Brustkorbs heißt untere Hälfte des Brustbeins.',
      ),
      FirstAidStep(
        '30-mal drücken.',
        detail: '5 bis 6 cm tief, 100 bis 120 Mal in der Minute, Arme gestreckt, senkrecht von oben. Den Brustkorb nach jedem Druck vollständig hochkommen lassen.',
      ),
      FirstAidStep(
        '2-mal beatmen.',
        detail: 'Kopf überstrecken, Nase zuhalten, eine Sekunde lang gleichmäßig einblasen, bis sich der Brustkorb sichtbar hebt. Zusammen höchstens 10 Sekunden.',
      ),
      FirstAidStep(
        'Weiter im Wechsel 30:2, ohne Pause.',
        detail: 'Bis der Rettungsdienst übernimmt, ein AED anweist abzusetzen, oder die Person normal zu atmen beginnt.',
      ),
      FirstAidStep(
        'Zu zweit alle zwei Minuten wechseln.',
        detail: 'Der Wechsel dauert Sekunden. Müde Hände drücken zu flach, ohne dass man es merkt.',
      ),
    ],
    cautions: [
      'Kannst oder willst du nicht beatmen, drücke ohne Unterbrechung weiter. Nur zu drücken ist deutlich besser als nichts zu tun.',
      'Nicht aufhören, um zu prüfen, ob es wirkt. Jede Unterbrechung lässt den Druck im Kreislauf zusammenfallen.',
      'Knackende Geräusche sind normal und kein Grund aufzuhören.',
    ],
    facts: [
      FirstAidFact('Takt', '100–120 pro Minute'),
      FirstAidFact('Tiefe', '5–6 cm'),
      FirstAidFact('Verhältnis', '30 Kompressionen : 2 Beatmungen'),
    ],
    drawing: FirstAidDrawing.compressionPoint,
    hasPacer: true,
    source: 'Reanimationsleitlinien 2025 des European Resuscitation Council (ERC), deutsche Fassung des German Resuscitation Council',
  ),
  FirstAidGuide(
    id: 'cpr-child',
    group: FirstAidGroup.lifeThreatening,
    title: 'Wiederbelebung – Kind und Säugling',
    when: 'Ein Kind unter der Pubertät oder ein Säugling reagiert nicht und atmet nicht normal.',
    callFirst: true,
    steps: [
      FirstAidStep(
        '112 anrufen, sobald das Kind nicht reagiert und nicht normal atmet.',
        detail: 'Telefon auf Lautsprecher und liegen lassen — so bleibst du beim Kind und hast die Hände frei. Bis 2021 galt hier noch: erst eine Minute wiederbeleben, dann anrufen. Seit den Leitlinien 2025 ist die Reihenfolge dieselbe wie beim Erwachsenen.',
      ),
      FirstAidStep(
        'Mit 5 Beatmungen beginnen, nicht mit dem Drücken.',
        detail: 'Bei Kindern steht das Herz fast immer wegen Sauerstoffmangel still, nicht umgekehrt. Beim Säugling Mund und Nase zugleich umschließen.',
      ),
      FirstAidStep(
        '15-mal drücken, dann 2-mal beatmen.',
        detail: 'Kind: ein oder zwei Handballen. Säugling: zwei Finger oder beide Daumen bei umfassten Händen.',
      ),
      FirstAidStep(
        'Ein Drittel des Brustkorbdurchmessers tief drücken.',
        detail: 'Etwa 5 cm beim Kind, etwa 4 cm beim Säugling. Takt wie beim Erwachsenen: 100 bis 120 in der Minute.',
      ),
      FirstAidStep('Weiter 15:2, bis Hilfe da ist.'),
    ],
    cautions: [
      'Traust du dir das Verhältnis 15:2 nicht zu, nimm 30:2 wie beim Erwachsenen. Das ist ausdrücklich erlaubt und weit besser als zu zögern.',
      'Zu vorsichtig zu drücken ist der häufigste Fehler. Ein Kind, dessen Herz steht, kann durch zu zaghaftes Drücken nicht gerettet werden.',
    ],
    facts: [
      FirstAidFact('Erst', '5 Beatmungen'),
      FirstAidFact('Dann', '15 Kompressionen : 2 Beatmungen'),
      FirstAidFact('Tiefe Kind', 'etwa 5 cm'),
      FirstAidFact('Tiefe Säugling', 'etwa 4 cm'),
      FirstAidFact('Takt', '100–120 pro Minute'),
    ],
    hasPacer: true,
    source: 'Reanimationsleitlinien 2025 des European Resuscitation Council (ERC), deutsche Fassung des German Resuscitation Council',
  ),
  FirstAidGuide(
    id: 'aed',
    group: FirstAidGroup.lifeThreatening,
    title: 'Defibrillator (AED)',
    when: 'Ein Gerät ist erreichbar, während wiederbelebt wird.',
    steps: [
      FirstAidStep('Einschalten. Das Gerät sagt ab jetzt alles an.'),
      FirstAidStep(
        'Weiter drücken, während die Elektroden aufgeklebt werden.',
        detail: 'Nur wenn du allein bist, unterbrich dafür kurz.',
      ),
      FirstAidStep(
        'Elektroden auf den nackten Brustkorb kleben, wie aufgedruckt.',
        detail: 'Eine unter das rechte Schlüsselbein, eine seitlich unter die linke Achsel. Brust nass? Vorher abtrocknen.',
      ),
      FirstAidStep('Während der Analyse niemanden berühren.'),
      FirstAidStep(
        'Schock empfohlen: sicherstellen, dass niemand die Person berührt, dann auslösen.',
      ),
      FirstAidStep(
        'Sofort danach weiter drücken.',
        detail: 'Ohne auf eine Reaktion zu warten. Das Gerät meldet sich nach zwei Minuten von selbst wieder.',
      ),
    ],
    cautions: [
      'Ein AED schockt nie jemanden, der keinen Schock braucht. Er analysiert selbst und gibt nur dann frei.',
      'Kinder unter acht Jahren: Kinderelektroden verwenden, wenn vorhanden. Sind keine da, nimm die für Erwachsene – das ist besser als kein Schock.',
      'Elektroden nicht auf einen Herzschrittmacher kleben; ein paar Zentimeter daneben genügen. Medikamentenpflaster vorher abziehen.',
    ],
    source: 'Reanimationsleitlinien 2025 des European Resuscitation Council (ERC), deutsche Fassung des German Resuscitation Council',
  ),
  FirstAidGuide(
    id: 'recovery-position',
    group: FirstAidGroup.lifeThreatening,
    title: 'Stabile Seitenlage',
    when: 'Die Person ist bewusstlos und atmet normal.',
    steps: [
      FirstAidStep('Neben der Person knien, Beine gerade legen.'),
      FirstAidStep(
        'Den nahen Arm im rechten Winkel nach oben legen, Handfläche nach oben.',
      ),
      FirstAidStep(
        'Den fernen Arm über die Brust ziehen, den Handrücken an die nahe Wange legen und dort festhalten.',
      ),
      FirstAidStep(
        'Das ferne Knie anwinkeln und die Person am Knie zu dir herüberziehen.',
      ),
      FirstAidStep(
        'Das obenliegende Bein so ausrichten, dass Hüfte und Knie im rechten Winkel liegen.',
      ),
      FirstAidStep(
        'Den Kopf nach hinten neigen, damit die Atemwege frei bleiben und der Mund der tiefste Punkt ist.',
      ),
      FirstAidStep(
        'Die Atmung weiter beobachten.',
        detail: 'Hört sie auf oder wird sie unnormal: auf den Rücken drehen und mit der Wiederbelebung beginnen.',
      ),
    ],
    cautions: [
      'Nach spätestens 30 Minuten auf die andere Seite drehen.',
      'Bei Verdacht auf eine Wirbelsäulenverletzung nur dann drehen, wenn die Atemwege anders nicht frei zu halten sind. Freie Atemwege haben Vorrang.',
    ],
    drawing: FirstAidDrawing.recoveryPosition,
    source: 'Reanimationsleitlinien 2025 des European Resuscitation Council (ERC), deutsche Fassung des German Resuscitation Council',
  ),
  FirstAidGuide(
    id: 'choking',
    group: FirstAidGroup.lifeThreatening,
    title: 'Ersticken',
    when: 'Jemand greift sich an den Hals, kann nicht sprechen, nicht husten, nicht atmen.',
    steps: [
      FirstAidStep(
        'Hustet die Person noch kräftig: zum Weiterhusten auffordern und dabeibleiben.',
        detail: 'Husten ist stärker als alles, was du tun kannst.',
      ),
      FirstAidStep(
        'Wird das Husten schwach: 5 Schläge zwischen die Schulterblätter.',
        detail: 'Oberkörper nach vorn beugen, mit dem Handballen kräftig schlagen, nach jedem Schlag prüfen.',
      ),
      FirstAidStep(
        'Bleibt es stecken: 5 Oberbauchkompressionen.',
        detail: 'Von hinten umfassen, eine Faust zwischen Nabel und Brustbeinende, mit der anderen Hand umgreifen, kräftig nach hinten und oben ziehen.',
      ),
      FirstAidStep('Im Wechsel weiter: 5 Schläge, 5 Kompressionen.'),
      FirstAidStep(
        'Wird die Person bewusstlos: 112 und sofort Wiederbelebung.',
      ),
    ],
    cautions: [
      'Bei Säuglingen unter einem Jahr keine Oberbauchkompressionen. Stattdessen 5 Rückenschläge in Bauchlage über dem Unterarm, dann 5 Brustkompressionen in Rückenlage.',
      'Nicht mit den Fingern blind im Mund nachfassen. Das schiebt den Fremdkörper meist tiefer.',
      'Nach Oberbauchkompressionen immer ärztlich untersuchen lassen, auch wenn alles gut aussieht – innere Verletzungen sind möglich.',
    ],
    facts: [
      FirstAidFact('Wechsel', '5 Rückenschläge, 5 Oberbauchkompressionen'),
      FirstAidFact('Säugling', '5 Rückenschläge, 5 Brustkompressionen'),
    ],
    drawing: FirstAidDrawing.choking,
    source: 'Reanimationsleitlinien 2025 des European Resuscitation Council (ERC), deutsche Fassung des German Resuscitation Council',
  ),
  FirstAidGuide(
    id: 'drowning',
    group: FirstAidGroup.lifeThreatening,
    title: 'Ertrinken',
    when: 'Jemand ist im Wasser in Not oder wurde gerade herausgeholt.',
    steps: [
      FirstAidStep(
        'Nicht ins Wasser gehen.',
        detail: 'Wer aktiv ertrinkt, klammert sich fest und zieht den Helfer mit hinunter. Geholfen wird vom Ufer oder vom Boot aus.',
      ),
      FirstAidStep(
        'Etwas Festes hinhalten oder etwas Schwimmfähiges zuwerfen.',
        detail: 'Stange, Ast, Ruder, Seil, Rettungsring.',
      ),
      FirstAidStep('Notruf 112.'),
      FirstAidStep('An Land laut ansprechen und die Atmung prüfen.'),
      FirstAidStep(
        'Atmet nicht normal: sofort wiederbeleben, 30 Drücken und 2 Beatmungen.',
        detail: 'Beim Ertrinken gehören die Beatmungen dazu – anders als beim Herzstillstand. Angefangen wird trotzdem mit dem Drücken.',
      ),
      FirstAidStep('Defibrillator: die Klebestellen vorher abtrocknen.'),
      FirstAidStep(
        'Atmet normal: stabile Seitenlage, den Kopf so, dass Flüssigkeit aus dem Mund ablaufen kann.',
      ),
      FirstAidStep(
        'Erbrochenes oder Fremdkörper nur herausholen, wenn sie die Atmung wirklich blockieren.',
      ),
    ],
    cautions: [
      'Keine Wiederbelebung im Wasser. Das ist etwas für eigens und wiederholt ausgebildete Retter, nicht für Ersthelfer.',
      'Eine aktiv ertrinkende Person nicht anfassen.',
      'Keinen Druck auf den Brustkorb, der das Atmen erschwert.',
    ],
    facts: [
      FirstAidFact('Verhältnis', '30 Drücken, 2 Beatmen'),
    ],
    source: 'International first aid, resuscitation and education guidelines 2025 der IFRC, Kapitel „Drowning"',
  ),
  FirstAidGuide(
    id: 'severe-bleeding',
    group: FirstAidGroup.injury,
    title: 'Starke Blutung',
    when: 'Blut fließt kräftig, spritzt oder durchtränkt die Kleidung.',
    callFirst: true,
    steps: [
      FirstAidStep(
        'Sofort direkt auf die Wunde drücken.',
        detail: 'Mit der Hand, mit einem Tuch, mit dem, was da ist. Handschuhe nur, wenn sie in Reichweite liegen.',
      ),
      FirstAidStep('112 anrufen oder anrufen lassen.'),
      FirstAidStep('Die blutende Stelle hochhalten, wenn es geht.'),
      FirstAidStep(
        'Druckverband anlegen und den Druck halten.',
        detail: 'Blutet es durch: nicht abnehmen, sondern eine weitere Lage darüber und weiter drücken.',
      ),
      FirstAidStep(
        'Lässt sich eine Blutung an Arm oder Bein so nicht stillen: Tourniquet.',
        detail: '5 bis 7 cm oberhalb der Wunde, nie über einem Gelenk. So fest, bis es nicht mehr blutet. Uhrzeit auf die Haut schreiben.',
      ),
      FirstAidStep(
        'Die Person flach hinlegen und warm halten.',
        detail: 'Auf Zeichen eines Schocks achten.',
      ),
    ],
    cautions: [
      'Ein einmal angelegtes Tourniquet bleibt, bis medizinisches Personal es abnimmt. Lösen und wieder festziehen ist gefährlicher als es zu lassen.',
      'Den Verband nicht anheben, um nachzusehen. Jedes Nachschauen reißt die gerade entstandene Gerinnung wieder auf.',
      'Einen tief steckenden Fremdkörper nicht herausziehen. Er verschließt die Wunde, die er gemacht hat. Ringsherum abpolstern.',
    ],
    drawing: FirstAidDrawing.bleeding,
    source:
        'Erste-Hilfe-Leitlinien 2025 des European Resuscitation Council (ERC)',
  ),
  FirstAidGuide(
    id: 'shock',
    group: FirstAidGroup.injury,
    title: 'Schock',
    when: 'Blass, kalte feuchte Haut, schneller flacher Puls, unruhig oder auffallend teilnahmslos – nach Blutverlust, Verbrennung oder starken Schmerzen.',
    callFirst: true,
    steps: [
      FirstAidStep('112 anrufen.'),
      FirstAidStep(
        'Die Ursache beheben, soweit möglich.',
        detail:
            'Eine Blutung zuerst stillen. Ohne das hilft die Lagerung wenig.',
      ),
      FirstAidStep(
        'Flach hinlegen und die Beine etwa 30 cm hochlegen.',
        detail: 'Nicht bei Verdacht auf Verletzungen von Wirbelsäule, Becken oder Beinen und nicht bei Atemnot.',
      ),
      FirstAidStep(
        'Warm halten.',
        detail: 'Eine Decke auch unter die Person, nicht nur darüber. Der Boden zieht mehr Wärme als die Luft.',
      ),
      FirstAidStep('Bleiben, ansprechen, Atmung beobachten.'),
    ],
    cautions: [
      'Nichts zu essen und nichts zu trinken geben, auch wenn ausdrücklich darum gebeten wird. Eine Operation könnte bevorstehen.',
      'Wird die Person bewusstlos und atmet normal: stabile Seitenlage. Atmet sie nicht normal: Wiederbelebung.',
    ],
    source:
        'Erste-Hilfe-Leitlinien 2025 des European Resuscitation Council (ERC)',
  ),
  FirstAidGuide(
    id: 'amputation',
    group: FirstAidGroup.injury,
    title: 'Abgetrenntes Körperteil',
    when: 'Ein Finger, eine Hand, ein Fuß ist ganz oder teilweise ab.',
    steps: [
      FirstAidStep('Notruf 112.'),
      FirstAidStep(
        'Blutet es stark: zuerst die Blutung stillen wie bei starker Blutung, und die Person gegen den Schock versorgen.',
      ),
      FirstAidStep(
        'Teilweise abgetrennt: das Glied so still wie möglich halten, möglichst in normaler Stellung, und mit sterilem Verband oder sauberem Tuch abdecken.',
      ),
      FirstAidStep(
        'Ganz abgetrennt: die Wunde mit sterilem Verband oder sauberem Tuch abdecken.',
      ),
      FirstAidStep(
        'Das abgetrennte Teil trocken und kühl halten.',
        detail: 'In einen sauberen, wasserdichten Beutel, fest verschließen, und diesen in einen größeren Behälter mit Eis und Wasser. Mit der Person in die Klinik schicken.',
      ),
      FirstAidStep(
        'Bei der Person bleiben und auch an sie denken, nicht nur an die Wunde.',
        detail: 'Psychische Erste Hilfe gilt hier für Verletzte, Angehörige – und für dich.',
      ),
    ],
    cautions: [
      'Das Körperteil nicht direkt ins Wasser und nicht direkt auf Eis. Das schädigt das Gewebe und kann das Wiederannähen unmöglich machen.',
      'Das ist eine große offene Wunde. Auf den eigenen Schutz achten.',
    ],
    source: 'International first aid, resuscitation and education guidelines 2025 der IFRC, Kapitel „Amputation"',
  ),
  FirstAidGuide(
    id: 'chest-abdomen-injury',
    group: FirstAidGroup.injury,
    title: 'Verletzung an Brust oder Bauch',
    when: 'Stich, Schuss, Pfählung oder stumpfe Gewalt gegen Rumpf.',
    steps: [
      FirstAidStep(
        'Bauch: flach hinlegen mit angezogenen Knien.',
        detail: 'Das nimmt Spannung aus der Bauchdecke.',
      ),
      FirstAidStep(
        'Brust: sitzend, leicht zur verletzten Seite geneigt.',
        detail: 'So arbeitet die gesunde Lunge am besten.',
      ),
      FirstAidStep('Blutung durch Druck stillen.'),
      FirstAidStep('Notruf 112.'),
      FirstAidStep(
        'Wunde am Bauch nach dem Stillen mit einem sauberen Verband abdecken.',
        detail: 'Treten Organe heraus, nicht zurückschieben – mit einem sauberen, feuchten Tuch abdecken.',
      ),
      FirstAidStep(
        'Beruhigen und Atmung, Kreislauf und Reaktion beobachten, besonders auf Anzeichen eines Schocks.',
      ),
    ],
    cautions: [
      'Eine offene Brustwunde nicht luftdicht verschließen. Sonst sammelt sich Luft im Brustkorb.',
      'Beim Druck auf eine Brustwunde die Wunde nicht ganz zudrücken.',
    ],
    source: 'International first aid, resuscitation and education guidelines 2025 der IFRC, Kapitel „Chest and abdomen injuries"',
  ),
  FirstAidGuide(
    id: 'burns',
    group: FirstAidGroup.injury,
    title: 'Verbrennung und Verbrühung',
    when: 'Hitze, Feuer, heiße Flüssigkeit, Strom oder Chemie haben die Haut verletzt.',
    steps: [
      FirstAidStep(
        'Die Ursache beenden.',
        detail: 'Flammen ersticken, Strom abschalten, durchnässte heiße Kleidung entfernen, solange sie nicht festklebt.',
      ),
      FirstAidStep(
        'Kleine Flächen 10 bis 20 Minuten kühlen.',
        detail: 'Fließendes lauwarmes Wasser, etwa 20 °C. Nur Hände, Füße, Gesicht oder einzelne Stellen.',
      ),
      FirstAidStep(
        'Ringe, Uhren und Armbänder sofort abnehmen.',
        detail: 'Bevor es anschwillt. Danach geht es nicht mehr.',
      ),
      FirstAidStep(
        'Locker und keimarm abdecken.',
        detail:
            'Brandwundenauflage oder ein sauberes Tuch. Nichts, was fasert.',
      ),
      FirstAidStep(
        'Große Flächen nicht kühlen, sondern zudecken und warm halten.',
        detail: 'Mehr als eine Handfläche des Verletzten. Kühlen führt dann zu Unterkühlung, die gefährlicher ist als die Verbrennung.',
      ),
      FirstAidStep(
        '112 bei großer Fläche, bei Gesicht, Händen, Genitalien oder Gelenken, bei Kindern, bei Strom und bei Chemie.',
      ),
    ],
    cautions: [
      'Kein Eis, kein Eiswasser. Das schädigt zusätzlich.',
      'Blasen nicht öffnen.',
      'Keine Salbe, kein Öl, kein Mehl, kein Puder, kein Hausmittel.',
      'Festgeklebte Kleidung nicht abziehen. Herumschneiden statt abreißen.',
    ],
    source:
        'Erste-Hilfe-Leitlinien 2025 des European Resuscitation Council (ERC)',
  ),
  FirstAidGuide(
    id: 'fracture',
    group: FirstAidGroup.injury,
    title: 'Knochenbruch, Verstauchung, Zerrung',
    when: 'Nach Sturz oder Stoß: Schmerz, Schwellung, ein Glied in falscher Stellung.',
    steps: [
      FirstAidStep('Die verletzte Stelle ruhig stellen.'),
      FirstAidStep(
        'In bequemer Lage abstützen, damit sich nichts bewegt.',
        detail: 'Hochlagern kann die Schwellung mindern.',
      ),
      FirstAidStep(
        'Bis zu 20 Minuten kühlen.',
        detail: 'Länger schadet der Haut. So früh wie möglich nach der Verletzung, und das Kühlelement immer in ein Tuch wickeln.',
      ),
      FirstAidStep(
        'Notruf 112 bei starken Schmerzen, starker Schwellung, Anzeichen eines Schocks, einem Bruch des Oberschenkels oder einem Glied in falscher Stellung.',
      ),
      FirstAidStep(
        'Offener Bruch: zuerst die Blutung stillen, dann das Glied stabilisieren.',
      ),
    ],
    cautions: [
      'Kühlelemente nie direkt auf die Haut.',
      'Kühlen abbrechen, wenn es zu schmerzhaft wird. Kehrt der Schmerz zurück und ist die Haut wieder normal warm, darf weiter gekühlt werden.',
      'Brüche und Ausrenkungen gehören immer in ärztliche Behandlung. Im Zweifel, ob Bruch, Verstauchung oder Zerrung: zum Arzt.',
    ],
    facts: [
      FirstAidFact('Kühlen', 'höchstens 20 Minuten'),
    ],
    source: 'International first aid, resuscitation and education guidelines 2025 der IFRC, Kapitel „Fractures, sprains and strains"',
  ),
  FirstAidGuide(
    id: 'spinal-injury',
    group: FirstAidGroup.injury,
    title: 'Verdacht auf Wirbelsäulenverletzung',
    when: 'Sturz aus Höhe, Kopfsprung, Verkehrsunfall – und Schmerz im Nacken oder Rücken.',
    steps: [
      FirstAidStep('Nicht bewegen. Die Person bleibt, wie du sie vorfindest.'),
      FirstAidStep(
        'Ist sie ansprechbar: beruhigen und bitten, sich so still wie möglich zu halten.',
      ),
      FirstAidStep(
        'Bei einem Kind, bei Benommenheit oder wenn jemand nicht folgen kann: den Kopf behutsam stützen.',
        detail: 'So, dass Nacken und Wirbelsäule sich nicht bewegen.',
      ),
      FirstAidStep('Notruf 112.'),
      FirstAidStep(
        'Bewusstlos und atmet normal: liegen lassen, Atemwege öffnen und den Kopf in dieser Lage stützen.',
      ),
      FirstAidStep(
        'Warm halten und Atmung und Reaktion bis zum Rettungsdienst beobachten.',
      ),
    ],
    cautions: [
      'Nicht umlagern, solange die Atmung normal ist und keine Gefahr besteht.',
      'Muss die Person doch bewegt werden, etwa wegen Gefahr: mit mindestens zwei Helfern, einer hält den Kopf in Linie mit der Wirbelsäule.',
      'Bei Verdacht auf Beckenbruch das Becken nicht wackeln und nicht drehen – das kann eine Blutung wieder in Gang bringen.',
    ],
    facts: [
      FirstAidFact('Wenn bewegt werden muss', 'mindestens zwei Helfer'),
    ],
    source: 'International first aid, resuscitation and education guidelines 2025 der IFRC, Kapitel „Spinal injury"',
  ),
  FirstAidGuide(
    id: 'head-injury',
    group: FirstAidGroup.injury,
    title: 'Kopfverletzung und Gehirnerschütterung',
    when: 'Schlag oder Sturz auf den Kopf.',
    steps: [
      FirstAidStep('Aus der Tätigkeit herausnehmen und ausruhen lassen.'),
      FirstAidStep(
        'Auf Anzeichen einer Gehirnerschütterung achten und darauf, ob Reaktion und Atmung sich ändern.',
      ),
      FirstAidStep(
        'Schwere Kopfverletzung: Notruf 112, beruhigen, Kopf und Nacken so still wie möglich halten.',
        detail: 'Liegt die Person, kannst du den Kopf mit Händen oder Knien ruhig halten.',
      ),
      FirstAidStep(
        'Reaktion und Atmung bis zum Eintreffen des Rettungsdienstes beobachten.',
      ),
    ],
    cautions: [
      'Nicht jeder Stoß gegen den Kopf ist eine Gehirnerschütterung. Fehlen die Anzeichen oder sind sie schwach, hilft Ausruhen – beobachtet werden muss die Person trotzdem.',
      'Eine Gehirnerschütterung kann sich über Stunden oder Tage erst entwickeln.',
      'Erst zurück an Arbeit, Steuer, Maschine oder Sport, wenn die Beschwerden weg sind.',
    ],
    source: 'International first aid, resuscitation and education guidelines 2025 der IFRC, Kapitel „Head injury and concussion"',
  ),
  FirstAidGuide(
    id: 'cuts-and-grazes',
    group: FirstAidGroup.injury,
    title: 'Wunden und Schürfwunden',
    when: 'Die kleine Verletzung, die es am häufigsten gibt.',
    steps: [
      FirstAidStep(
        'Blutet es stark: zuerst Druck auf die Wunde, dann weiter hier.',
      ),
      FirstAidStep(
        'Mit sauberem Trinkwasser spülen, am besten lauwarm und aus dem Hahn.',
        detail: 'Kein Hahn da: eine saubere, unbenutzte Wasserflasche anstechen – das gibt einen sanften Strahl.',
      ),
      FirstAidStep(
        'Schmutzreste mit Wasser und einer sauberen Kompresse entfernen.',
      ),
      FirstAidStep(
        'Die Haut ringsum trocknen und die Wunde abdecken.',
        detail: 'Verband, Folie, Hydrokolloid – oder schlicht ein Pflaster.',
      ),
    ],
    cautions: [
      'Ist der Tetanusschutz nicht sicher, zum Arzt. Nach einer schmutzigen Wunde gilt eine Auffrischung alle fünf Jahre, sonst alle zehn.',
      'Den Verband nur wechseln, wenn er sichtbar durchgefeuchtet ist. Ist er sauber, bleibt er drauf.',
    ],
    facts: [
      FirstAidFact('Tetanus nach schmutziger Wunde', 'alle 5 Jahre'),
    ],
    source: 'International first aid, resuscitation and education guidelines 2025 der IFRC, Kapitel „Cuts and grazes"',
  ),
  FirstAidGuide(
    id: 'nosebleed',
    group: FirstAidGroup.injury,
    title: 'Nasenbluten',
    when: 'Blut aus der Nase, von selbst oder nach einem Stoß.',
    steps: [
      FirstAidStep(
        'Hinsetzen und den Kopf leicht nach vorn neigen.',
        detail: 'Nach vorn, nicht in den Nacken.',
      ),
      FirstAidStep(
        'Die Nasenflügel zusammendrücken, 10 bis 15 Minuten am Stück.',
      ),
      FirstAidStep(
        'Hört es nach 15 Minuten nicht auf, oder wird der Person schwindlig vom Blutverlust: ärztliche Hilfe.',
      ),
      FirstAidStep(
        'Nach einem Stoß und mit Anzeichen einer Hirnverletzung, verformter Nase, Gesichtsbruch – oder wenn die Person Blutverdünner nimmt: sofort Notruf 112.',
      ),
    ],
    cautions: [
      'Den Kopf nicht in den Nacken legen. Das Blut läuft dann in den Rachen.',
      'Zum Arzt, wenn es sich in kurzer Zeit häuft – oder wenn ein Kind unter zwei Jahren Nasenbluten hatte.',
    ],
    facts: [
      FirstAidFact('Drücken', '10 bis 15 Minuten am Stück'),
    ],
    source: 'International first aid, resuscitation and education guidelines 2025 der IFRC, Kapitel „Nosebleeds"',
  ),
  FirstAidGuide(
    id: 'animal-bite',
    group: FirstAidGroup.injury,
    title: 'Tierbiss',
    when: 'Gebissen von Hund, Katze oder einem wilden Tier.',
    steps: [
      FirstAidStep('Blutet es: zuerst Druck auf die Wunde.'),
      FirstAidStep('Danach weiter wie bei einer Wunde: spülen und abdecken.'),
      FirstAidStep(
        'Zum Arzt, wenn die Wunde genäht werden muss oder der Tetanusschutz fehlt.',
      ),
      FirstAidStep(
        'Bei einem wilden Tier und fehlendem Tollwutschutz: ärztliche Hilfe suchen.',
      ),
    ],
    cautions: [
      'Tierbisse können Krankheiten übertragen. Auch eine kleine Bisswunde ist keine gewöhnliche kleine Wunde.',
      'Auf Zeichen einer Entzündung achten: wird es warm oder schmerzt es stärker, zum Arzt.',
    ],
    source: 'International first aid, resuscitation and education guidelines 2025 der IFRC, Kapitel „Mammal bites"',
  ),
  FirstAidGuide(
    id: 'tick',
    group: FirstAidGroup.injury,
    title: 'Zeckenstich',
    when: 'Eine Zecke sitzt in der Haut.',
    steps: [
      FirstAidStep(
        'So schnell wie möglich entfernen.',
        detail: 'Mit einer Zeckenkarte oder -zange nach deren Anleitung. Sonst mit einer Pinzette so dicht wie möglich an der Haut fassen und gleichmäßig und fest herausziehen.',
      ),
      FirstAidStep('Die Stelle mit Wasser und Seife waschen.'),
      FirstAidStep(
        'Datum und Ort des Stichs aufschreiben und die Stelle im Auge behalten.',
      ),
      FirstAidStep(
        'Zum Arzt bei Fieber, unerklärlicher Müdigkeit, Gelenkschmerzen oder wenn ein Ausschlag auftritt.',
        detail: 'Der Ausschlag bei Borreliose ist ein Fleck mit einem Ring darum. Er tritt aber nicht immer auf.',
      ),
    ],
    cautions: [
      'Den Körper der Zecke nicht quetschen. Das drückt die Erreger in die Haut.',
      'Keine Chemie und keine Hitze, um die Zecke zu betäuben oder zu töten.',
      'Ein Zeckenstich wird anders behandelt als ein Schlangenbiss.',
    ],
    source: 'International first aid, resuscitation and education guidelines 2025 der IFRC, Kapitel „Insect bites or stings"',
  ),
  FirstAidGuide(
    id: 'insect-bite',
    group: FirstAidGroup.injury,
    title: 'Insektenstich',
    when: 'Biene, Wespe, Hornisse, Mücke.',
    steps: [
      FirstAidStep('Beruhigen und vom Kratzen abhalten.'),
      FirstAidStep(
        'Steckt der Stachel noch: so schnell wie möglich heraus.',
        detail: 'Mit etwas Flachem abschaben – Bankkarte, stumpfe Messerseite.',
      ),
      FirstAidStep('Die Stelle gründlich mit Wasser reinigen.'),
      FirstAidStep(
        'Kühlen, gegen Schwellung, Juckreiz und Schmerz.',
        detail: 'Sitzt der Stich an der Hand: Ringe abnehmen.',
      ),
      FirstAidStep(
        'Sofort Notruf 112 bei einem Stich im Mund oder Rachen, oder bei Anzeichen einer allergischen Reaktion.',
        detail: 'Im Mund kann die Schwellung die Atemwege verschließen. Bis Hilfe da ist, einen Eiswürfel lutschen lassen.',
      ),
    ],
    cautions: [
      'Den Stachel nicht mit Pinzette oder Fingern fassen. Das drückt den Giftbeutel aus.',
      'Nicht kratzen.',
      'Bei Atemnot, Schwellung im Gesicht oder Kreislaufproblemen ist es ein allergischer Schock – siehe die eigene Anleitung dazu.',
    ],
    source: 'International first aid, resuscitation and education guidelines 2025 der IFRC, Kapitel „Insect bites or stings"',
  ),
  FirstAidGuide(
    id: 'snakebite',
    group: FirstAidGroup.injury,
    title: 'Schlangenbiss',
    when: 'In Deutschland die Kreuzotter – oder eine gehaltene Schlange.',
    steps: [
      FirstAidStep('Weg von der Schlange, an einen sicheren Platz.'),
      FirstAidStep('Bequem hinlegen und so wenig wie möglich bewegen lassen.'),
      FirstAidStep('Notruf 112.'),
      FirstAidStep(
        'Schmuck, Uhr und enge Kleidung abnehmen, bevor es anschwillt.',
        detail: 'Dabei das Glied so wenig wie möglich bewegen.',
      ),
      FirstAidStep('Die Bissstelle markieren und die Uhrzeit notieren.'),
      FirstAidStep(
        'Reaktion und Atmung beobachten, ruhig zusprechen und bleiben.',
      ),
    ],
    cautions: [
      'Nichts davon hilft, und alles davon kann schaden: abbinden, Gift aussaugen, kühlen, die Stelle reiben, die Wunde aufschneiden.',
      'Schlangen werden gehandelt und reisen. Es kann eine Art sein, die hier nicht vorkommt.',
    ],
    source: 'International first aid, resuscitation and education guidelines 2025 der IFRC, Kapitel „Snakebites"',
  ),
  FirstAidGuide(
    id: 'jellyfish',
    group: FirstAidGroup.injury,
    title: 'Quallenkontakt',
    when: 'Brennende Striemen nach dem Baden in der See.',
    steps: [
      FirstAidStep(
        'Die Nesselzellen von der Haut entfernen und sich dabei selbst schützen.',
      ),
      FirstAidStep('Die Stelle mit Meerwasser abspülen.'),
      FirstAidStep(
        'Wärme auf die Stelle, 20 bis 30 Minuten.',
        detail: 'Warmes Wasser oder ein Wärmekissen, höchstens 45 °C. Heiß genug gegen den Schmerz, nicht so heiß, dass es verbrennt.',
      ),
      FirstAidStep('Zum Arzt bei Tetanusgefahr oder wenn der Schmerz bleibt.'),
    ],
    cautions: [
      'Nicht mit Süßwasser abspülen – Meerwasser.',
      'Bei einer schweren allergischen Reaktion sofort Notruf 112.',
    ],
    facts: [
      FirstAidFact('Wärme', 'höchstens 45 °C, 20 bis 30 Minuten'),
    ],
    source: 'International first aid, resuscitation and education guidelines 2025 der IFRC, Kapitel „Aquatic animal injuries"',
  ),
  FirstAidGuide(
    id: 'blisters',
    group: FirstAidGroup.injury,
    title: 'Blasen an den Füßen',
    when: 'Nach langem Gehen – und damit die Verletzung, die eine Flucht zu Fuß beendet.',
    steps: [
      FirstAidStep(
        'Die Blase und die Haut ringsum mit sauberem Wasser waschen und vorsichtig trocken tupfen.',
      ),
      FirstAidStep('Ist die Blase heil: mit einem Blasenpflaster abdecken.'),
      FirstAidStep(
        'Ist sie von selbst aufgegangen: die Wunde reinigen und steril abdecken.',
        detail: 'Muss weitergelaufen werden, hilft eine zweite Lage Polster darüber.',
      ),
    ],
    cautions: [
      'Zum Arzt, wenn daraus eine offene Wunde wird oder sie sich entzündet – warm, zunehmend schmerzhaft, Fieber.',
      'Bei Diabetes oder geschwächter Abwehr früher zum Arzt: solche Wunden entzünden sich leichter und heilen schlechter.',
    ],
    source: 'International first aid, resuscitation and education guidelines 2025 der IFRC, Kapitel „Friction blisters"',
  ),
  FirstAidGuide(
    id: 'dental-avulsion',
    group: FirstAidGroup.injury,
    title: 'Ausgeschlagener Zahn',
    when: 'Ein bleibender Zahn ist ganz herausgeschlagen.',
    steps: [
      FirstAidStep(
        'Die Blutung im Mund mit einer Kompresse aus Gaze oder sauberer Watte stillen.',
      ),
      FirstAidStep(
        'Den Zahn suchen und nur an der Krone anfassen, nicht an der Wurzel.',
      ),
      FirstAidStep(
        'Feucht aufbewahren.',
        detail: 'Salzlösung, eine Trinklösung oder Frischhaltefolie – bei Folie genug Speichel dazu, damit der Zahn nicht austrocknet. Sonst H-Milch oder der eigene Speichel.',
      ),
      FirstAidStep(
        'So schnell wie möglich zum Zahnarzt oder in die Notaufnahme, den Zahn mitnehmen.',
      ),
    ],
    cautions: [
      'Den Zahn nicht im Mund transportieren, außer die Person ist erwachsen, ganz wach und kann es sicher. Der freie Atemweg geht vor allem anderen.',
      'Ein ausgeschlagener Zahn kann auf eine weitere Verletzung hindeuten – etwa am Kopf. Die geht vor.',
    ],
    source: 'International first aid, resuscitation and education guidelines 2025 der IFRC, Kapitel „Dental avulsion"',
  ),
  FirstAidGuide(
    id: 'flash-eye',
    group: FirstAidGroup.injury,
    title: 'Verblitzte Augen',
    when: 'Stunden nach Schweißen, Höhensonne, Schnee oder See: Schmerz, als läge Sand im Auge.',
    steps: [
      FirstAidStep('Weg von der Lichtquelle und beruhigen.'),
      FirstAidStep('Kontaktlinsen herausnehmen lassen.'),
      FirstAidStep(
        'Die Augen schonen: drinnen bleiben, Sonnenbrille, Augen so viel wie möglich geschlossen halten.',
        detail: 'Ein kühles, feuchtes Tuch auf die geschlossenen Lider. Kochsalzlösung oder Augentropfen halten sie feucht.',
      ),
      FirstAidStep(
        'Bessert es sich in 24 Stunden nicht, oder wird es schlimmer: zum Arzt.',
      ),
    ],
    cautions: [
      'Nicht reiben.',
      'Das kommt nicht nur im Schnee vor – auch am Wasser, am Strand und beim Schweißen.',
    ],
    source: 'International first aid, resuscitation and education guidelines 2025 der IFRC, Kapitel „Flash eye"',
  ),
  FirstAidGuide(
    id: 'stroke',
    group: FirstAidGroup.illness,
    title: 'Schlaganfall',
    when: 'Plötzlich: hängender Mundwinkel, kraftloser Arm, verwaschene Sprache, Sehstörung oder stärkster Kopfschmerz aus dem Nichts.',
    callFirst: true,
    steps: [
      FirstAidStep('Lächeln lassen.', detail: 'Hängt eine Gesichtshälfte?'),
      FirstAidStep(
        'Beide Arme nach vorn heben lassen, Handflächen nach oben.',
        detail: 'Sinkt einer ab oder dreht sich?',
      ),
      FirstAidStep(
        'Einen einfachen Satz nachsprechen lassen.',
        detail: 'Klingt es verwaschen, oder werden Worte vertauscht?',
      ),
      FirstAidStep(
        'Eines davon auffällig: sofort 112.',
        detail: 'Und sagen, dass es ein Schlaganfall sein könnte.',
      ),
      FirstAidStep(
        'Die Uhrzeit merken, zu der es angefangen hat.',
        detail: 'Das ist die wichtigste Auskunft, die du geben kannst – sie entscheidet über die Behandlung. War die Person beim Aufwachen schon betroffen, gilt der Zeitpunkt, zu dem sie zuletzt gesund gesehen wurde.',
      ),
      FirstAidStep('Oberkörper leicht erhöht lagern, bei Bewusstsein.'),
    ],
    cautions: [
      'Nichts zu essen und nichts zu trinken geben. Das Schlucken kann gestört sein, ohne dass man es sieht.',
      'Nicht abwarten, ob es besser wird. Auch wenn die Zeichen wieder verschwinden, ist es ein Notfall.',
      'Nicht selbst fahren und nicht fahren lassen.',
    ],
    facts: [
      FirstAidFact('F – Face', 'Gesicht hängt'),
      FirstAidFact('A – Arms', 'Arm sinkt ab'),
      FirstAidFact('S – Speech', 'Sprache verwaschen'),
      FirstAidFact('T – Time', 'Sofort 112, Uhrzeit merken'),
    ],
    drawing: FirstAidDrawing.face,
    source:
        'Erste-Hilfe-Leitlinien 2025 des European Resuscitation Council (ERC)',
  ),
  FirstAidGuide(
    id: 'heart-attack',
    group: FirstAidGroup.illness,
    title: 'Herzinfarkt',
    when: 'Druck, Enge oder Schmerz in der Brust, länger als ein paar Minuten – oft mit Atemnot, Übelkeit, kaltem Schweiß und Angst.',
    callFirst: true,
    steps: [
      FirstAidStep('Sofort 112. Nicht abwarten.'),
      FirstAidStep('Oberkörper hoch lagern, halb sitzend.'),
      FirstAidStep('Beengende Kleidung öffnen, Fenster auf.'),
      FirstAidStep(
        'Bei der Person bleiben und ruhig mit ihr sprechen.',
        detail:
            'Angst treibt den Puls und damit den Sauerstoffbedarf des Herzens.',
      ),
      FirstAidStep(
        'Jede Anstrengung vermeiden.',
        detail: 'Nicht laufen lassen, nicht Treppen steigen lassen.',
      ),
      FirstAidStep(
        'Bewusstlos und keine normale Atmung: sofort Wiederbelebung.',
      ),
    ],
    cautions: [
      'Bei Frauen, älteren Menschen und Diabetikern fehlt der typische Brustschmerz oft. Dann stehen Atemnot, Übelkeit, Oberbauchschmerz oder plötzliche Erschöpfung im Vordergrund.',
      'Nicht selbst ins Krankenhaus fahren. Im Rettungswagen beginnt die Behandlung, im eigenen Auto nicht.',
      'Kein Medikament geben, das nicht dieser Person verordnet wurde.',
    ],
    source:
        'Erste-Hilfe-Leitlinien 2025 des European Resuscitation Council (ERC)',
  ),
  FirstAidGuide(
    id: 'seizure',
    group: FirstAidGroup.illness,
    title: 'Krampfanfall',
    when: 'Jemand stürzt, wird steif und zuckt, oft mit verdrehten Augen und Speichel am Mund.',
    steps: [
      FirstAidStep('Platz schaffen und Gefährliches wegräumen.'),
      FirstAidStep('Etwas Weiches unter den Kopf legen.'),
      FirstAidStep(
        'Auf die Uhr sehen.',
        detail: 'Wie lange der Anfall dauert, ist die Auskunft, nach der als Erstes gefragt wird.',
      ),
      FirstAidStep(
        'Warten, bis es vorbei ist.',
        detail:
            'Die meisten Anfälle enden nach ein bis zwei Minuten von selbst.',
      ),
      FirstAidStep(
        'Danach stabile Seitenlage und dabeibleiben.',
        detail: 'Die Verwirrung danach dauert oft länger als der Anfall.',
      ),
    ],
    cautions: [
      'Nichts in den Mund schieben. Nichts. Die Zunge kann nicht verschluckt werden, abgebrochene Zähne und gebrochene Finger dagegen schon.',
      'Nicht festhalten und die Zuckungen nicht unterdrücken.',
      'Nichts zu trinken geben, solange die Person nicht wieder klar ist.',
    ],
    facts: [
      FirstAidFact('112 rufen, wenn', 'der Anfall länger als 5 Minuten dauert'),
      FirstAidFact('Ebenso, wenn', 'es der erste Anfall ist'),
      FirstAidFact(
        'Ebenso, wenn',
        'ein zweiter folgt, ohne dass die Person zwischendurch zu sich kommt',
      ),
      FirstAidFact('Ebenso bei', 'Verletzung, Schwangerschaft, Wasser'),
    ],
    source:
        'Erste-Hilfe-Leitlinien 2025 des European Resuscitation Council (ERC)',
  ),
  FirstAidGuide(
    id: 'anaphylaxis',
    group: FirstAidGroup.illness,
    title: 'Allergischer Schock',
    when: 'Nach Stich, Nuss, Medikament oder Lebensmittel: Quaddeln, schwellendes Gesicht, pfeifende Atmung, Engegefühl im Hals, Kreislaufzusammenbruch.',
    callFirst: true,
    steps: [
      FirstAidStep('Sofort 112 und sagen, dass es eine Allergie ist.'),
      FirstAidStep(
        'Nach dem Notfallset der Person fragen oder danach suchen.',
        detail: 'Wer das weiß, trägt meist einen Autoinjektor bei sich.',
      ),
      FirstAidStep(
        'Den Autoinjektor in die Außenseite des Oberschenkels drücken.',
        detail: 'Durch die Kleidung hindurch möglich. Die Anleitung steht auf dem Gerät und ist in Sekunden gelesen.',
      ),
      FirstAidStep(
        'Flach hinlegen, Beine hoch.',
        detail: 'Bei Atemnot dagegen aufrecht sitzen lassen. Nicht plötzlich aufstehen lassen.',
      ),
      FirstAidStep(
        'Keine Besserung nach 5 bis 15 Minuten: zweite Dosis, wenn eine zweite da ist.',
      ),
      FirstAidStep('Bewusstlos und keine normale Atmung: Wiederbelebung.'),
    ],
    cautions: [
      'Auch wenn es rasch besser wird: immer in die Klinik. Die Beschwerden kommen in einem Teil der Fälle nach Stunden zurück.',
      'Ein Autoinjektor darf nur bei der Person angewendet werden, für die er verordnet ist – oder auf Anweisung der Leitstelle.',
    ],
    source:
        'Erste-Hilfe-Leitlinien 2025 des European Resuscitation Council (ERC)',
  ),
  FirstAidGuide(
    id: 'asthma',
    group: FirstAidGroup.illness,
    title: 'Asthmaanfall',
    when: 'Pfeifende, schwere Atmung und Enge in der Brust.',
    steps: [
      FirstAidStep(
        'Bequem hinsetzen lassen und beruhigen.',
        detail: 'Oft hilft aufrecht sitzen, nach vorn gelehnt, die Arme aufgestützt.',
      ),
      FirstAidStep('Beim eigenen Spray helfen. Enge Kleidung öffnen.'),
      FirstAidStep(
        'Notruf 112.',
        detail: 'Wenn kein Spray da ist und der Anfall mehrere Minuten dauert; wenn das Spray nach wenigen Minuten nicht wirkt; bei schwerer Atemnot; bei bläulichen Lippen, Ohren, Fingern oder Zehen; bei Verwirrtheit; oder wenn die Atmung langsamer und leiser wird.',
      ),
      FirstAidStep(
        'Kein Spray da: ruhig halten, aufrecht setzen, frische Luft, weg vom Auslöser.',
      ),
      FirstAidStep(
        'Dableiben, bis der Anfall vorbei ist, und beim Nachdosieren nach der eigenen Verordnung helfen.',
      ),
    ],
    cautions: [
      'Nur das Spray, das dieser Person selbst verordnet ist.',
      'Wird die Atmung langsamer und leiser oder die Person müde, ist das keine Besserung.',
    ],
    source: 'International first aid, resuscitation and education guidelines 2025 der IFRC, Kapitel „Asthma attack"',
  ),
  FirstAidGuide(
    id: 'hypoglycaemia',
    group: FirstAidGroup.illness,
    title: 'Unterzuckerung',
    when: 'Bekannter Diabetes, dazu Zittern, Schwitzen, Verwirrtheit oder plötzliche Gereiztheit.',
    steps: [
      FirstAidStep('Bequem hinsetzen oder hinlegen lassen.'),
      FirstAidStep(
        'Eigenen Traubenzucker geben: 15 bis 20 Gramm.',
        detail: 'Sonst ein zuckerhaltiges Getränk ohne Süßstoff, etwa Fruchtsaft, oder Zucker – etwa drei Teelöffel oder drei Stück Weingummi.',
      ),
      FirstAidStep(
        'Nach 15 Minuten keine Besserung: dieselbe Menge noch einmal.',
      ),
      FirstAidStep(
        'Nach etwa 30 Minuten keine Besserung, oder die Person wird bewusstlos: Notruf 112.',
      ),
    ],
    cautions: [
      'Nur etwas zu essen oder zu trinken geben, wenn die Person ansprechbar ist und schlucken kann.',
      'Keine Diät- oder Light-Getränke. Da ist kein Zucker drin.',
    ],
    facts: [
      FirstAidFact('Zucker', '15 bis 20 g'),
      FirstAidFact('Nachlegen nach', '15 Minuten'),
    ],
    source: 'International first aid, resuscitation and education guidelines 2025 der IFRC, Kapitel „Diabetic emergency (hypoglycemia)"',
  ),
  FirstAidGuide(
    id: 'croup',
    group: FirstAidGroup.illness,
    title: 'Pseudokrupp',
    when: 'Ein Kind wacht nachts mit bellendem Husten und pfeifendem Einatmen auf.',
    steps: [
      FirstAidStep(
        'Ruhig bleiben und das Kind beruhigen, meist im Sitzen.',
        detail: 'Das ist kein Nebensatz: bleibst du ruhig, wird es ruhiger, und die Atemnot lässt nach.',
      ),
      FirstAidStep('Fieber messen und, wenn vorhanden, behandeln.'),
      FirstAidStep(
        'Feuchte, warme Luft einatmen lassen.',
        detail: 'Neben der laufenden Dusche sitzen oder über eine Schüssel mit heißem Wasser beugen – nicht so heiß, dass es verbrüht.',
      ),
      FirstAidStep(
        'Atmung und Reaktion genau beobachten. Bei schwerem oder anhaltendem Anfall: Notruf 112.',
      ),
    ],
    cautions: [
      'Sofort 112 bei schwerer Atemnot: aufrecht und vorgebeugt, Mund offen, Hals- und Schultermuskeln arbeiten mit, Nasenflügel beben, über dem Brustbein zieht es ein.',
      'Aus leicht kann in wenigen Stunden schwer werden. Und es gibt eine ähnlich aussehende Entzündung des Kehldeckels, die sofort in ärztliche Hände gehört. Im Zweifel anrufen.',
    ],
    source: 'International first aid, resuscitation and education guidelines 2025 der IFRC, Kapitel „Croup"',
  ),
  FirstAidGuide(
    id: 'faint',
    group: FirstAidGroup.illness,
    title: 'Drohende Ohnmacht',
    when: 'Schwarz vor Augen, blass, schwindlig – noch bei Bewusstsein.',
    steps: [
      FirstAidStep('Hinsetzen oder hinlegen, dort wo niemand fallen kann.'),
      FirstAidStep(
        'Muskeln anspannen lassen, das treibt das Blut zum Kopf.',
        detail: 'In die Hocke gehen; oder die Beine kreuzen und Bein-, Bauch- und Gesäßmuskeln fest anspannen. Die untere Körperhälfte wirkt besser als die obere.',
      ),
      FirstAidStep('Wer liegt: die Beine hochhalten, wenn er das möchte.'),
      FirstAidStep('Dableiben, beobachten und herausfinden, woran es liegt.'),
    ],
    cautions: [
      'Nach einer Ohnmacht nur langsam wieder aufstehen und weitermachen – sonst kippt die Person gleich noch einmal um.',
      'Ist jemand gestürzt, an Kopf und Knochen denken.',
      'Wer ohnmächtig wird, kommt sehr schnell wieder zu sich. Bleibt er ohne Reaktion, ist es keine Ohnmacht: Atmung prüfen.',
    ],
    source: 'International first aid, resuscitation and education guidelines 2025 der IFRC, Kapitel „Feeling faint"',
  ),
  FirstAidGuide(
    id: 'fever',
    group: FirstAidGroup.illness,
    title: 'Fieber',
    when: 'Erhöhte Temperatur, Frösteln, Schwäche.',
    steps: [
      FirstAidStep('Ruhen lassen und leicht anziehen.'),
      FirstAidStep('Zu trinken geben – Schwitzen kostet Flüssigkeit.'),
      FirstAidStep(
        'Oft braucht es kein Medikament.',
        detail: 'Geht es der Person schlecht, kann Paracetamol in der empfohlenen Dosis das Fieber senken. Auch Abwaschen mit lauwarmem Wasser hilft, solange es nicht unangenehm ist.',
      ),
      FirstAidStep('Den Zustand beobachten und auf neue Zeichen achten.'),
    ],
    cautions: [
      'Nicht mit Kleidung und Decken einpacken.',
      'Nicht mit kaltem Wasser abwaschen. Das ist unangenehm und hält die Wärme im Körper.',
      'Paracetamol ist das Mittel der Wahl. Ibuprofen kann den Magen reizen und die Nieren schädigen. Zwei Fiebermittel nebeneinander nur mit genauem Plan, sonst wird doppelt dosiert.',
    ],
    source: 'International first aid, resuscitation and education guidelines 2025 der IFRC, Kapitel „Fever"',
  ),
  FirstAidGuide(
    id: 'childbirth',
    group: FirstAidGroup.illness,
    title: 'Geburt ohne Hilfe',
    when: 'Die Wehen kommen, und Rettungsdienst oder Hebamme sind nicht da oder kommen nicht durch.',
    steps: [
      FirstAidStep(
        'Hilfe holen – Klinik, Rettungsdienst, Hebamme – und die Person entscheiden lassen, wen sie dabeihaben will.',
      ),
      FirstAidStep(
        'Erste Phase: einen sicheren, ruhigen, geschützten Platz schaffen.',
        detail: 'Die Haltung wählt die Gebärende: sitzen, stehen, umhergehen.',
      ),
      FirstAidStep(
        'Wärme und Berührung anbieten, wenn sie das möchte.',
        detail: 'Den Rücken massieren; ein warmer Umschlag oder eine Wärmflasche auf Kreuzbein, Bauch oder Damm kann den Schmerz mindern.',
      ),
      FirstAidStep(
        'Zweite Phase: eine bequeme, möglichst aufrechte Haltung.',
        detail: 'Liegt sie auf dem Rücken, ein kleines Kissen unter die rechte Hüfte – sonst drückt das Kind auf große Blutgefäße.',
      ),
      FirstAidStep(
        'Hände mit Wasser und Seife waschen und ein sauberes Tuch unterlegen.',
      ),
      FirstAidStep(
        'Den Kopf des Kindes beim Austreten stützen.',
        detail: 'Neugeborene sind glitschig. Mund und Nase von Flüssigkeit und Schleim frei wischen.',
      ),
      FirstAidStep(
        'Das Kind mit einem sauberen Tuch abtrocknen, einwickeln, den Kopf bedecken und sofort auf Brust oder Bauch der Mutter legen.',
        detail: 'Die Mutter genauso warm halten.',
      ),
      FirstAidStep(
        'Dritte Phase: die Nachgeburt abwarten und aufheben.',
        detail: 'Sie wird von Fachleuten noch gebraucht.',
      ),
    ],
    cautions: [
      'Von hier an sind es zwei Patienten: die Mutter und das Kind.',
      'Nichts erzwingen und nicht ziehen. Was hier steht, ist Begleiten, nicht Entbinden.',
    ],
    source: 'International first aid, resuscitation and education guidelines 2025 der IFRC, Kapitel „Emergency childbirth"',
  ),
  FirstAidGuide(
    id: 'hypothermia',
    group: FirstAidGroup.environment,
    title: 'Unterkühlung',
    when: 'Zittern, kalte blasse Haut, Verlangsamung, Verwirrung – nach Kälte, Nässe oder Wind. Hört das Zittern auf, wird es gefährlich.',
    steps: [
      FirstAidStep('Aus der Kälte holen, vor Wind und Nässe schützen.'),
      FirstAidStep('Nasse Kleidung entfernen, notfalls aufschneiden.'),
      FirstAidStep(
        'In Decken einpacken, auch unter der Person.',
        detail: 'Kopf mit einpacken. Der Boden zieht die meiste Wärme.',
      ),
      FirstAidStep('Wach und schluckfähig: warme, gezuckerte Getränke.'),
      FirstAidStep(
        'Wärme auf Rumpf, Hals und Kopf, nicht auf Arme und Beine.',
        detail: 'Wärmflasche oder Wärmepad, immer mit einem Tuch dazwischen.',
      ),
      FirstAidStep(
        '112 bei Verwirrung, aufhörendem Zittern oder Schläfrigkeit.',
      ),
    ],
    cautions: [
      'Arme und Beine nicht reiben und nicht aktiv erwärmen. Das treibt kaltes Blut zum Herzen.',
      'So wenig wie möglich bewegen. Ein stark unterkühltes Herz kann durch Erschütterung stehenbleiben.',
      'Kein Alkohol. Er fühlt sich warm an und kühlt aus.',
      'Bei schwerer Unterkühlung Atmung und Puls bis zu einer Minute prüfen – beides kann kaum wahrnehmbar sein. Niemand ist tot, bevor er nicht warm und tot ist.',
    ],
    source:
        'Erste-Hilfe-Leitlinien 2025 des European Resuscitation Council (ERC)',
  ),
  FirstAidGuide(
    id: 'heat',
    group: FirstAidGroup.environment,
    title: 'Hitzeerschöpfung und Hitzschlag',
    when: 'Nach Hitze oder Anstrengung: Schwäche, Kopfschmerz, Übelkeit. Kommt heiße trockene Haut, Verwirrung oder Bewusstlosigkeit dazu, ist es ein Hitzschlag und lebensbedrohlich.',
    steps: [
      FirstAidStep('In den Schatten oder in einen kühlen Raum bringen.'),
      FirstAidStep('Hinlegen, Beine hoch, Kleidung öffnen.'),
      FirstAidStep(
        'Bei Bewusstsein: in kleinen Schlucken Wasser trinken lassen.',
      ),
      FirstAidStep(
        'Kühlen: feuchte Tücher, Luft zufächeln, kaltes Wasser auf Nacken, Achseln und Leisten.',
      ),
      FirstAidStep(
        '112 bei Verwirrung, heißer trockener Haut, Erbrechen oder Bewusstlosigkeit.',
        detail: 'Das ist ein Hitzschlag. Weiterkühlen, bis der Rettungsdienst da ist.',
      ),
    ],
    cautions: [
      'Nichts zu trinken geben, wenn die Person verwirrt oder nicht ganz wach ist.',
      'Kein Alkohol und nichts Koffeinhaltiges.',
      'Ein Hitzschlag ist kein stärkerer Sonnenbrand. Ohne Behandlung endet er tödlich.',
    ],
    source: 'Bundeszentrale für gesundheitliche Aufklärung und Erste-Hilfe-Leitlinien 2025 des ERC',
  ),
  FirstAidGuide(
    id: 'poisoning',
    group: FirstAidGroup.environment,
    title: 'Vergiftung',
    when: 'Etwas wurde geschluckt, eingeatmet, verschüttet oder in die Augen bekommen, das dort nicht hingehört.',
    steps: [
      FirstAidStep('Eigene Sicherheit: bei Gas und Rauch nicht hineingehen.'),
      FirstAidStep(
        'Beim Giftnotruf anrufen. Bei Bewusstlosigkeit oder Atemnot zuerst 112.',
      ),
      FirstAidStep(
        'Bereitlegen, was gefragt wird.',
        detail: 'Was, wie viel, wann, wie alt und wie schwer ist die Person, welche Beschwerden.',
      ),
      FirstAidStep(
        'Die Verpackung, den Rest und gegebenenfalls Erbrochenes aufheben.',
      ),
      FirstAidStep(
        'Haut oder Augen betroffen: 10 bis 15 Minuten mit fließendem Wasser spülen.',
        detail: 'Beim Auge vom inneren zum äußeren Winkel, damit nichts ins gesunde Auge läuft.',
      ),
      FirstAidStep('Bewusstlos und normale Atmung: stabile Seitenlage.'),
    ],
    cautions: [
      'Kein Erbrechen auslösen. Bei Säuren, Laugen und Schäumern richtet der Weg zurück mehr Schaden an als der Weg hinunter.',
      'Keine Milch. Sie beschleunigt die Aufnahme vieler Gifte.',
      'Kein Salzwasser.',
      'Die Nummern sind ein gespeicherter Stand. Prüfe sie, solange du Netz hast, und trage die für dich zuständige in die Notfallkontakte ein.',
    ],
    facts: poisonCentres,
    source: 'Giftinformationszentren der Länder, Bundesinstitut für Risikobewertung',
  ),
  FirstAidGuide(
    id: 'frostbite',
    group: FirstAidGroup.environment,
    title: 'Erfrierungen',
    when:
        'Weiße, harte, gefühllose Stellen an Fingern, Zehen, Nase oder Ohren.',
    steps: [
      FirstAidStep(
        'Zuerst vor Unterkühlung schützen.',
        detail: 'An einen wärmeren Ort bringen, nasse Kleidung ausziehen, trocken und warm halten.',
      ),
      FirstAidStep(
        'Schmuck vorsichtig abnehmen, solange das ohne Verletzung geht.',
      ),
      FirstAidStep(
        'Die Stelle behutsam in körperwarmem Wasser aufwärmen.',
        detail: 'Meist etwa 30 Minuten, bis sie wieder durchwärmt ist.',
      ),
      FirstAidStep(
        'Mit steriler Gaze verbinden. Sind mehrere Finger oder Zehen betroffen, Gaze dazwischenlegen.',
      ),
      FirstAidStep(
        'Die Leitlinie stellt zusätzlich ein Schmerzmittel zur Erwägung.',
        detail: 'Hochdosiertes Ibuprofen, 400 bis 800 mg, oder – wenn das nicht da ist – niedrig dosierte Acetylsalicylsäure, 75 bis 81 mg. Das kann die Heilung verbessern. Die Mengen sind die der Leitlinie, nicht die dieser App.',
      ),
    ],
    cautions: [
      'Nicht reiben und nicht grob anfassen – das schädigt die Haut.',
      'Nicht an direkte Hitze wie Heizlüfter oder Herd.',
      'Blasen nicht öffnen.',
      'Nur aufwärmen, wenn ein erneutes Durchfrieren ausgeschlossen ist. Ärztliche Hilfe ist bei Erfrierungen immer nötig.',
    ],
    facts: [
      FirstAidFact('Aufwärmen', 'körperwarmes Wasser, ~30 Minuten'),
    ],
    source: 'International first aid, resuscitation and education guidelines 2025 der IFRC, Kapitel „Frostbite"',
  ),
  FirstAidGuide(
    id: 'dehydration',
    group: FirstAidGroup.environment,
    title: 'Austrocknung',
    when: 'Nach Durchfall, Erbrechen, Fieber oder Hitze: Durst, wenig und dunkler Urin, Schwäche.',
    steps: [
      FirstAidStep('Beruhigen und reichlich zu trinken geben.'),
      FirstAidStep('Leichter Fall: Wasser genügt.'),
      FirstAidStep(
        'Schwerer Fall: eine Trinklösung.',
        detail: 'Ist keine da: Apfelsaft, Kokoswasser oder Wasser.',
      ),
      FirstAidStep(
        'Trinklösung selbst ansetzen: auf einen Liter Trinkwasser einen halben Teelöffel Salz und sechs Teelöffel Zucker.',
      ),
      FirstAidStep(
        'Notruf 112, wenn die Person verwirrt wird oder nicht mehr ansprechbar ist.',
      ),
    ],
    cautions: [
      'Nichts Alkoholisches.',
      'Keine Trinklösung bei einer diabetischen Überzuckerung – das verschlimmert die Austrocknung.',
      'Ärztlichen Rat holen bei Säuglingen, Kindern und alten Menschen, wenn mehr verloren geht als hineinkommt, wenn kaum noch oder sehr dunkler Urin kommt, bei Fieber oder Hitzeerschöpfung, und im Zweifel.',
    ],
    facts: [
      FirstAidFact('Trinklösung je Liter', 'halber TL Salz, 6 TL Zucker'),
      FirstAidFact('Kinder von 2 bis 5 Jahren', '10 ml je kg'),
    ],
    source: 'International first aid, resuscitation and education guidelines 2025 der IFRC, Kapitel „Dehydration"',
  ),
  FirstAidGuide(
    id: 'psychological-first-aid',
    group: FirstAidGroup.mentalDistress,
    title: 'Psychische Erste Hilfe',
    when: 'Jemand ist nach einem Unglück verstört, erstarrt oder außer sich. Diese Seite gilt für alle folgenden.',
    steps: [
      FirstAidStep(
        'Erst die Sicherheit, dann alles andere.',
        detail: 'Ist der Ort nicht sicher, wird hier nicht angefangen – weder für dich noch für die andere Person.',
      ),
      FirstAidStep(
        'Hinsehen: Wer braucht Hilfe, und wer am dringendsten?',
        detail: 'Verletzungen zuerst. Wer still in der Ecke sitzt, wird dabei leicht übersehen; laut ist nicht gleich schlimm.',
      ),
      FirstAidStep(
        'Ruhig zugehen, dich mit Namen vorstellen und sagen, dass du helfen willst.',
        detail: 'Auf gleicher Höhe, ohne das Telefon in der Hand.',
      ),
      FirstAidStep(
        'Zuhören und jede Reaktion gelten lassen.',
        detail: 'Weinen, Wut, Schweigen, Gleichgültigkeit – alles davon kommt vor, und nichts davon muss weggeredet werden.',
      ),
      FirstAidStep(
        'Fragen, was jetzt gebraucht wird, statt es zu erraten.',
        detail: 'Offene Fragen, und die Entscheidung bleibt bei der Person. Wer wieder selbst entscheidet, kommt zur Ruhe.',
      ),
      FirstAidStep(
        'Für das Nächstliegende sorgen: Wärme, etwas zu trinken, ein ruhiger Platz.',
        detail: 'Bei Kindern zählt vor allem dazu, die Bezugsperson wiederzufinden.',
      ),
      FirstAidStep(
        'Verbinden: zu Angehörigen, zu verlässlicher Auskunft, zu weiterer Hilfe.',
        detail: 'Sagen, was du weißt und was du nicht weißt. Unklarheit macht mehr Angst als eine schlechte Nachricht.',
      ),
    ],
    cautions: [
      'Nicht nach Einzelheiten des Erlebten fragen. Wer erzählen will, erzählt von selbst – und darf jederzeit aufhören.',
      'Nicht deuten und nicht bewerten. Psychische Erste Hilfe ist kein Gespräch über Ursachen und keine Therapie.',
      'Keine Hilfe gegen den Willen der Person, und keine Berührung ohne Erlaubnis.',
      'Nicht weggehen, um Hilfe zu holen, ohne vorher jemanden gefunden zu haben, der nach der Person sieht.',
    ],
    facts: [
      FirstAidFact('Telefonseelsorge, rund um die Uhr', '0800 111 0 111'),
      FirstAidFact('Telefonseelsorge, europaweit', '116 123'),
      FirstAidFact('Ärztlicher Bereitschaftsdienst', '116 117'),
    ],
    source: 'International first aid, resuscitation and education guidelines 2025 der IFRC, Kapitel „Psychological first aid" (Look – Listen – Link nach der WHO)',
  ),
  FirstAidGuide(
    id: 'suicidal-ideation',
    group: FirstAidGroup.mentalDistress,
    title: 'Suizidgedanken',
    when: 'Jemand sagt oder zeigt, dass er nicht mehr leben will.',
    steps: [
      FirstAidStep('Ernst nehmen. Jede Äußerung, auch eine beiläufige.'),
      FirstAidStep(
        'Direkt danach fragen.',
        detail: 'Darüber zu sprechen erhöht die Wahrscheinlichkeit nicht, dass jemand es tut. Offen und behutsam zu fragen nimmt der Sache das Verbotene.',
      ),
      FirstAidStep(
        'Von Anfang an sagen, dass du nichts für dich behalten kannst, was lebensgefährlich ist.',
        detail: 'Das gehört an den Anfang, nicht ans Ende – sonst ist es ein Vertrauensbruch statt einer Bedingung.',
      ),
      FirstAidStep(
        'Die Person nicht allein lassen.',
        detail: 'Am Telefon: nach dem Aufenthaltsort fragen und nach jemandem, dem sie vertraut.',
      ),
      FirstAidStep(
        'Alles wegräumen lassen, womit sie sich verletzen könnte.',
        detail: 'Medikamente, Werkzeug, Waffen. Wenn jemand aus dem Haushalt dabei hilft, umso besser.',
      ),
      FirstAidStep(
        'Den Ort sicher machen.',
        detail: 'Ein ruhiger Raum weiter unten im Haus, Fenster zu, weg von allem Gefährlichen.',
      ),
      FirstAidStep(
        'Gemeinsam Hilfe holen – im Beisein anrufen, nicht als Auftrag mitgeben.',
        detail: 'Telefonseelsorge, Hausarzt, sozialpsychiatrischer Dienst, psychiatrische Klinik.',
      ),
      FirstAidStep(
        'Bei unmittelbarer Gefahr oder nach einem Versuch: 112.',
        detail: 'Nach einem Versuch zuerst die körperliche Erste Hilfe – Blutung, Vergiftung, Bewusstlosigkeit.',
      ),
    ],
    cautions: [
      'Nicht versprechen, es für dich zu behalten. Dieses Versprechen kann man nicht halten.',
      'Nicht bewerten und nicht widersprechen. Was hilft, ist Zuhören.',
      'Nicht weggehen, um Hilfe zu holen. Erst dafür sorgen, dass jemand bleibt.',
      'Diese Seite ersetzt keine Ausbildung. Sie soll aufmerksam machen, nicht zum Fachmann.',
    ],
    facts: [
      FirstAidFact('Telefonseelsorge, rund um die Uhr', '0800 111 0 111'),
      FirstAidFact('Telefonseelsorge, zweite Nummer', '0800 111 0 222'),
      FirstAidFact('Telefonseelsorge, europaweit', '116 123'),
      FirstAidFact('Kinder- und Jugendtelefon', '116 111'),
      FirstAidFact('Notruf bei unmittelbarer Gefahr', '112'),
    ],
    source: 'International first aid, resuscitation and education guidelines 2025 der IFRC, Kapitel „Suicidal ideation"; Rufnummern der TelefonSeelsorge Deutschland und der Nummer gegen Kummer',
  ),
  FirstAidGuide(
    id: 'anxiety-panic',
    group: FirstAidGroup.mentalDistress,
    title: 'Angst und Panikattacke',
    when: 'Herzrasen, Atemnot, Enge in der Brust, Todesangst – und nach Minuten geht es von selbst zurück.',
    steps: [
      FirstAidStep('Vorstellen und sagen, dass du bleibst.'),
      FirstAidStep(
        'An einen ruhigen Platz gehen, weg von Zuschauern.',
        detail: 'Enge Kleidung öffnen.',
      ),
      FirstAidStep(
        'Fragen, ob die Person so etwas schon einmal hatte.',
        detail: 'Wer die Attacke wiedererkennt, hat die Hälfte der Angst schon verloren.',
      ),
      FirstAidStep(
        'Sagen, dass es eine Reaktion auf Anspannung ist und von selbst nachlässt.',
        detail: 'Der Höhepunkt ist nach zehn bis fünfzehn Minuten vorbei.',
      ),
      FirstAidStep('Langsam und leise sprechen, in kurzen Sätzen.'),
      FirstAidStep(
        'Voratmen und mitatmen lassen.',
        detail: 'Auf eins durch die Nase ein, auf drei durch den Mund aus, und in den Bauch atmen lassen.',
      ),
      FirstAidStep(
        'Sagen, dass daran nichts peinlich ist und niemand verrückt wird.',
      ),
      FirstAidStep(
        'Bleiben, bis es vorbei ist.',
        detail: 'Kommt es öfter vor oder richtet jemand sein Leben danach ein, zum Arzt raten: dagegen gibt es wirksame Hilfe.',
      ),
    ],
    cautions: [
      'Keine Tüte vor den Mund. Die Leitlinien 2025 sprechen für dieses und ähnliche Hausmittel keine Empfehlung aus; empfohlen ist das Vor- und Mitatmen.',
      'Nicht „beruhige dich" und nicht „da ist doch nichts". Die Angst ist echt, auch wenn die Gefahr es nicht ist.',
      'Im Zweifel, ob Panikattacke oder Notfall: 112. Brustschmerz und Atemnot können auch vom Herzen kommen.',
    ],
    facts: [
      FirstAidFact('Höhepunkt der Attacke', 'nach 10 bis 15 Minuten'),
      FirstAidFact('Atmen', 'ein auf 1, aus auf 3'),
      FirstAidFact('Telefonseelsorge, europaweit', '116 123'),
    ],
    source: 'International first aid, resuscitation and education guidelines 2025 der IFRC, Kapitel „Anxiety and panic"',
  ),
  FirstAidGuide(
    id: 'traumatic-event',
    group: FirstAidGroup.mentalDistress,
    title: 'Nach einem schweren Erlebnis',
    when: 'Kurz nach Unglück, Unfall oder Gewalt – bei Betroffenen und bei Helfern.',
    steps: [
      FirstAidStep(
        'Zuerst das Körperliche: Blutung stillen, versorgen, wiederbeleben.',
        detail: 'Ruhig und zugewandt dabei bleiben. Beides geht zugleich.',
      ),
      FirstAidStep('In kurzen, einfachen Sätzen sagen, was du gerade tust.'),
      FirstAidStep('Dableiben, zuhören, und die Gefühle gelten lassen.'),
      FirstAidStep(
        'Die Person über ihre Versorgung mitentscheiden lassen.',
        detail: 'Wer gefragt wird und wählen darf, bekommt ein Stück Kontrolle zurück.',
      ),
      FirstAidStep('Angehörige oder Freunde dazuholen, wenn es geht.'),
      FirstAidStep(
        'Dem Rettungsdienst sagen, wie es der Person körperlich und seelisch geht.',
      ),
    ],
    cautions: [
      'Nicht zum Erzählen drängen und nicht nach Einzelheiten fragen.',
      'Starke Reaktionen in den ersten Tagen sind gewöhnlich und noch keine Krankheit.',
      'Sie können auch erst nach Wochen oder Monaten kommen. Hält es an oder wird es schlimmer, gehört es ärztlich abgeklärt.',
    ],
    facts: [
      FirstAidFact('Ärztlicher Bereitschaftsdienst', '116 117'),
      FirstAidFact('Telefonseelsorge, europaweit', '116 123'),
    ],
    source: 'International first aid, resuscitation and education guidelines 2025 der IFRC, Kapitel „Traumatic event"',
  ),
  FirstAidGuide(
    id: 'acute-grief',
    group: FirstAidGroup.mentalDistress,
    title: 'Akute Trauer',
    when: 'Jemand hat gerade erfahren, dass ein Mensch gestorben ist.',
    steps: [
      FirstAidStep(
        'Vorstellen und sagen, dass du da bist, wenn die Person dich nicht kennt.',
      ),
      FirstAidStep(
        'An einen sicheren Platz gehen und Raum schaffen.',
        detail: 'Niemand soll sich umstellt fühlen.',
      ),
      FirstAidStep('Direkt fragen, womit du helfen kannst.'),
      FirstAidStep(
        'Ganz da sein und jede Reaktion gelten lassen.',
        detail: 'Schock, Wut, Schuldgefühle, Gleichgültigkeit – bei einem plötzlichen Tod ist all das gewöhnlich.',
      ),
      FirstAidStep(
        'Fragen, ob die Person den Verstorbenen sehen möchte, wenn das möglich ist.',
        detail: 'Vorher sagen, wie er aussieht. Zeit beim Verstorbenen erleichtert das Trauern und nimmt Schuldgefühle.',
      ),
      FirstAidStep('Helfen, Angehörige zu erreichen, statt allein zu bleiben.'),
      FirstAidStep(
        'Zu Pausen ermutigen – etwas tun, das für eine Weile ablenkt.',
      ),
    ],
    cautions: [
      'Nicht allein lassen, ohne dich vergewissert zu haben, dass es geht.',
      'Keine Vergleiche und keine Fristen. Trauer hat keine Dauer, nach der sie vorbei zu sein hätte.',
      'Nicht sagen, was die Person jetzt zu fühlen hätte.',
    ],
    facts: [
      FirstAidFact('Telefonseelsorge, rund um die Uhr', '0800 111 0 111'),
      FirstAidFact('Telefonseelsorge, europaweit', '116 123'),
    ],
    source: 'International first aid, resuscitation and education guidelines 2025 der IFRC, Kapitel „Acute grief"',
  ),
];
